import { ClipboardCheck, FileCheck2, HandCoins, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router';
const procedures = [
  { icon: HandCoins, title: 'Receive school fees and donations', steps: ['Check the student charge or donor record before recording money received. Record each instalment separately.', 'For scholarships or discounts, retain the reason and the authorised decision. Discuss fee support privately with the family.', 'Keep pledges and gifts in kind separate from cash receipts. Record donor restrictions in the designation and supporting agreement.', 'Issue a tax receipt only after verifying the organisation’s approval and the gift’s eligibility.'] },
  { icon: ShieldCheck, title: 'Review and pay expenses', steps: ['Prepare the invoice, purpose, amount, tax, budget, and supporting document references.', 'Submit for independent review. The preparer or submitter cannot approve or reject their own expense.', 'Review donor restrictions, procurement evidence, conflicts of interest, and available budget before approval.', 'Record actual payments with the date, account or cash box, and bank or voucher reference. Retain posted receipts.'] },
  { icon: ClipboardCheck, title: 'Reconcile at month end', steps: ['Compare every receipt and payment with bank statements and cash counts. Investigate timing differences and missing documents.', 'Reconcile each restricted fund separately using the donor agreement and approved budget. A campaign total is not a restricted-fund ledger.', 'Review outstanding fees sensitively, approved unpaid invoices, budget variances, and payroll obligations.', 'Have another officer review and sign the reconciliation and reports. Retain a dated copy with the source evidence.'] },
  { icon: FileCheck2, title: 'Know what the reports show', steps: ['Cash reports use receipt and payment dates, with UTC calendar boundaries. They exclude in-kind gifts and other currencies.', 'Cumulative net movement is receipts less payments for the selected period. It is not a reconciled bank balance.', 'Budget commitments include gross approved invoices, including tax, even if those invoices have not been paid.', 'Bank reconciliation, restricted-fund accounting, period closing, and refund journals must currently be maintained in the organisation’s accounting records.'] },
];
export default function FinanceProcedures() {
  return <div className="mx-auto max-w-5xl space-y-6 pb-10">
    <header><p className="text-xs font-semibold uppercase tracking-widest text-academic-teal">Finance practice</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">From receipt to review</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">A working guide for school and community finance officers. Apply your board-approved policies, donor agreements and local requirements alongside these steps.</p></header>
    <div className="grid gap-5 lg:grid-cols-2">{procedures.map(({ icon: Icon, title, steps }, index) => <section key={title} className="border border-border bg-card p-5"><div className="flex items-start gap-3"><Icon className="mt-1 h-5 w-5 shrink-0 text-academic-teal" aria-hidden="true" /><h2 className="text-lg font-semibold">{index + 1}. {title}</h2></div><ol className="mt-5 list-decimal space-y-3 pl-5 text-sm leading-6">{steps.map(step => <li key={step} className="pl-1">{step}</li>)}</ol></section>)}</div>
    <p className="text-sm text-muted-foreground">Keep donor and family details within authorised finance records. Share donor reports with only the personal information required.</p>
    <Link to="/financial/reports/monthly" className="inline-block text-sm font-semibold text-academic-teal underline underline-offset-4">Open the monthly finance report</Link>
  </div>;
}
