import type { OfficialLanguageQuestCourse, OfficialLanguageQuestChallenge } from "./languageQuestImportedCourses";

export type GedScienceV2Visual =
  | { type: "process"; title: string; steps: string[]; caption?: string }
  | { type: "table"; title: string; headers: string[]; rows: string[][]; caption?: string }
  | { type: "formula"; title: string; formula: string; variables?: Array<{ marker: string; text: string }>; example?: string }
  | { type: "bar"; title: string; items: Array<{ label: string; value: number; unit?: string }>; caption?: string }
  | { type: "line"; title: string; points: Array<{ x: number; y: number; label?: string }>; xLabel: string; yLabel: string; caption?: string }
  | { type: "layers"; title: string; layers: Array<{ name: string; detail: string }>; caption?: string }
  | { type: "compare"; title: string; leftTitle: string; rightTitle: string; left: string[]; shared?: string[]; right: string[] }
  | { type: "evidence"; title: string; claim: string; evidence: string[]; reasoning: string };

export interface GedScienceV2LessonSeed {
  title: string;
  description: string;
  summary: string;
  objectives: string[];
  explanation: string[];
  visual: GedScienceV2Visual;
  keyTerms: Array<{ marker: string; text: string }>;
  gedStrategy: string;
  checkpoint: string;
  questions: Array<{ question: string; correct: string; distractors: string[]; explanation: string; hint?: string }>;
}

const PREFIX = "SCIENCE_V2::";
const encode = (lesson: GedScienceV2LessonSeed) => PREFIX + JSON.stringify({
  version: 2,
  summary: lesson.summary,
  objectives: lesson.objectives,
  explanation: lesson.explanation,
  keyTerms: lesson.keyTerms,
  visual: lesson.visual,
  gedStrategy: lesson.gedStrategy,
  checkpoint: lesson.checkpoint,
});

const q = (question: string, correct: string, distractors: string[], explanation: string, hint?: string) => ({ question, correct, distractors, explanation, hint });

function challenges(lesson: GedScienceV2LessonSeed): OfficialLanguageQuestChallenge[] {
  return lesson.questions.map((item, index) => {
    const options = [item.correct, ...item.distractors].slice(0, 4);
    // Deterministic rotation avoids putting the correct answer in the same slot every time.
    const shift = index % options.length;
    const rotated = [...options.slice(shift), ...options.slice(0, shift)];
    return {
      type: "SELECT",
      question: item.question,
      explanation: item.explanation,
      hint: item.hint || "Use the labels, units, variables, or evidence shown in the learning section before choosing.",
      options: rotated.map((text) => ({
        text,
        correct: text === item.correct,
        emoji: null,
        audioText: null,
      })),
    };
  });
}

function lesson(seed: GedScienceV2LessonSeed) {
  return {
    title: seed.title,
    description: seed.description,
    conceptIntro: encode(seed),
    challenges: challenges(seed),
  };
}

const lifeScience: GedScienceV2LessonSeed[] = [
  {
    title: "Interpret Illustrations",
    description: "Read labels, arrows, keys, and spatial relationships in biological illustrations.",
    summary: "Scientific illustrations are evidence displays. Their labels and arrows tell you which structures, directions, and relationships matter.",
    objectives: ["Read titles, labels, keys, and arrows", "Identify structure-function relationships", "Use a visual rather than memory alone"],
    explanation: ["Start with the title, then scan every label before reading the question. Arrows can indicate movement, direction, sequence, or a relationship between structures.", "On the GED, a labeled illustration often contains information that is not repeated in the text. Treat every label as potential evidence."],
    visual: { type: "table", title: "Bacterial cell — labeled structures", headers: ["Label", "Structure", "Function"], rows: [["A", "Cell membrane", "Controls what enters and leaves"], ["B", "Cytoplasm", "Fluid interior where reactions occur"], ["C", "Ribosome", "Builds proteins"], ["D", "Flagellum", "Helps movement"]], caption: "Read the label and function together before answering." },
    keyTerms: [{ marker: "structure", text: "a physical part of an organism or cell" }, { marker: "function", text: "the job performed by a structure" }],
    gedStrategy: "Cover the answer choices for a moment and locate the requested label in the visual first. Then compare that evidence with the options.",
    checkpoint: "If the question asks what a ribosome does, which column of the table gives the direct evidence?",
    questions: [q("Which labeled structure builds proteins?", "C — Ribosome", ["A — Cell membrane", "B — Cytoplasm", "D — Flagellum"], "The table directly labels the ribosome as the structure that builds proteins."), q("Which structure helps the bacterium move?", "D — Flagellum", ["A — Cell membrane", "B — Cytoplasm", "C — Ribosome"], "The flagellum is labeled as the movement structure."), q("What is the best first step when reading a science illustration?", "Read the title and all labels", ["Ignore labels", "Guess from memory", "Choose the longest answer"], "Titles and labels establish what the visual represents and how its parts are identified.")],
  },
  {
    title: "Identify Main Idea and Details",
    description: "Separate a passage's central point from evidence and examples.",
    summary: "The main idea is the broad point supported by important details; details explain, quantify, or exemplify that point.",
    objectives: ["Distinguish central ideas from supporting details", "Recognize evidence that supports a claim", "Avoid choosing an interesting but narrow detail as the main idea"],
    explanation: ["Ask what most of the passage is about, not which fact is most memorable. A main idea should cover most major details without being broader than the evidence.", "Supporting details may be observations, measurements, examples, comparisons, or explanations."],
    visual: { type: "process", title: "From evidence to main idea", steps: ["Detail 1", "Detail 2", "Detail 3", "Supported main idea"], caption: "Several related details point toward one broader statement." },
    keyTerms: [{ marker: "main idea", text: "the central point of a passage" }, { marker: "supporting detail", text: "a fact or example that develops the main idea" }],
    gedStrategy: "After reading, state the passage in one sentence. Then test whether each major detail fits beneath that sentence.",
    checkpoint: "Would a single unusual example usually be broad enough to serve as the main idea?",
    questions: [q("Which statement best describes a supporting detail?", "A fact or example that explains the main idea", ["The title of every passage", "Any sentence with a number", "An unrelated conclusion"], "Supporting details develop or support the central point."), q("Which main idea is strongest?", "A statement supported by most major details", ["A statement about one minor example", "A claim absent from the passage", "The longest sentence"], "A main idea should account for the passage's major evidence."), q("Why should you compare a proposed main idea with the details?", "To check that the details actually support it", ["To make it longer", "To remove all evidence", "To avoid reading the passage"], "The relationship between main idea and evidence is the key test.")],
  },
  {
    title: "Interpret Tables",
    description: "Use headings, units, rows, columns, and footnotes to extract evidence.",
    summary: "Tables organize data by categories. Accurate interpretation depends on tracing the correct row, column, and unit.",
    objectives: ["Read row and column headings", "Use units correctly", "Compare values without mixing categories"],
    explanation: ["First identify what each column measures and what each row represents. Then locate the exact intersection requested by the question.", "Units can completely change the meaning of a value. Do not compare percentages, counts, masses, or rates as if they were interchangeable."],
    visual: { type: "table", title: "Seedling growth after 14 days", headers: ["Light per day", "Mean height (cm)", "Leaves"], rows: [["4 h", "8", "3"], ["8 h", "13", "5"], ["12 h", "17", "6"]], caption: "Follow the requested row and column before comparing." },
    keyTerms: [{ marker: "row", text: "horizontal set of related table entries" }, { marker: "column", text: "vertical category of values" }, { marker: "unit", text: "measurement scale attached to a value" }],
    gedStrategy: "Finger-trace or mentally trace the requested row and column to their intersection; then check the unit.",
    checkpoint: "What is the mean height for seedlings receiving 8 hours of light?",
    questions: [q("What is the mean height at 8 hours of light?", "13 cm", ["8 cm", "17 cm", "5 cm"], "The 8 h row and mean-height column intersect at 13 cm."), q("Which treatment produced the most leaves?", "12 h of light", ["4 h of light", "8 h of light", "All were equal"], "The leaf counts are 3, 5, and 6; 6 is highest."), q("Before comparing table values, what should you verify?", "The headings and units", ["The font size", "The row color", "The answer-letter pattern"], "Headings and units define what each value means.")],
  },
  {
    title: "Identify Cause and Effect",
    description: "Distinguish causes from results and avoid confusing sequence with causation.",
    summary: "A cause contributes to an event; an effect is the result. Sequence alone does not prove cause.",
    objectives: ["Identify causal chains", "Recognize causal signal words", "Distinguish correlation or sequence from demonstrated causation"],
    explanation: ["Science passages often describe multi-step chains in which one effect becomes the next cause. Track each link separately.", "Words such as because, therefore, results in, and leads to often signal causation, but the evidence must still support the connection."],
    visual: { type: "process", title: "Response to a skin injury", steps: ["Cut in skin", "Bacteria may enter", "Immune response", "Redness and swelling"], caption: "Each arrow represents a causal link described by the model." },
    keyTerms: [{ marker: "cause", text: "a factor that produces or contributes to a change" }, { marker: "effect", text: "the result of a cause" }],
    gedStrategy: "Ask 'what happened because of this?' for effects and 'what made this happen?' for causes.",
    checkpoint: "In the chain shown, what directly triggers the immune response?",
    questions: [q("What directly causes the immune response in the model?", "Bacteria entering the tissue", ["The skin staying intact", "The swelling that happens later", "Lower body temperature"], "Bacterial entry comes immediately before and triggers the immune response."), q("Which phrase most strongly signals an effect?", "As a result", ["For example", "In contrast", "Similarly"], "'As a result' explicitly introduces an outcome."), q("Does one event occurring after another automatically prove causation?", "No, sequence alone is not enough", ["Yes, always", "Only if the second event is larger", "Only in biology"], "Temporal order can be consistent with causation but does not by itself establish it.")],
  },
  {
    title: "Interpret Graphs and Maps",
    description: "Use axes, scales, legends, and spatial patterns to interpret visual data.",
    summary: "Graphs show quantitative patterns; maps show spatial patterns. Titles, axes, scales, and legends define the evidence.",
    objectives: ["Identify trends", "Read graph axes and scales", "Use map legends and symbols"],
    explanation: ["Read the title and both axes before interpreting the pattern. Check whether the axis starts at zero or uses an unusual interval.", "On maps, a legend tells you what colors or symbols represent. Spatial clustering can suggest a pattern but may require further evidence to explain its cause."],
    visual: { type: "line", title: "Reported cases over four weeks", points: [{ x: 1, y: 10, label: "10" }, { x: 2, y: 18, label: "18" }, { x: 3, y: 27, label: "27" }, { x: 4, y: 38, label: "38" }], xLabel: "Week", yLabel: "Cases", caption: "The overall trend is upward." },
    keyTerms: [{ marker: "trend", text: "overall direction of change" }, { marker: "scale", text: "the numerical spacing used on an axis or map" }, { marker: "legend", text: "key explaining symbols or colors" }],
    gedStrategy: "Describe the graph in words before looking at the answer choices: increasing, decreasing, stable, cyclical, or mixed.",
    checkpoint: "Does the graph show a general increase or decrease?",
    questions: [q("What overall trend is shown?", "Cases generally increase over time", ["Cases generally decrease", "Cases remain constant", "The graph has no pattern"], "The plotted values rise from 10 to 38 across the four weeks."), q("Which graph feature tells what the vertical values measure?", "The y-axis label", ["The legend only", "The title font", "The x-axis tick marks only"], "The y-axis label identifies the measured vertical variable."), q("On a map, what explains the meaning of symbols?", "The legend or key", ["The north arrow only", "The border", "The page number"], "The legend defines map symbols and colors.")],
  },
  {
    title: "Interpret Diagrams",
    description: "Follow arrows, sequences, hierarchies, and flows in scientific diagrams.",
    summary: "Diagrams simplify relationships. Arrow direction and labels indicate how matter, energy, or information moves.",
    objectives: ["Follow directional arrows", "Identify producers and consumers", "Infer relationships shown by sequence"],
    explanation: ["Do not assume every arrow means the same thing. In a food chain, arrows commonly represent transfer of energy from the eaten organism to the eater.", "Read the legend or caption when available to determine what the arrows mean."],
    visual: { type: "process", title: "Food-energy pathway", steps: ["Sun", "Grass (producer)", "Grasshopper", "Sparrow", "Hawk"], caption: "Energy moves through the biological chain in the arrow direction." },
    keyTerms: [{ marker: "producer", text: "organism that captures energy to make organic matter" }, { marker: "consumer", text: "organism that obtains energy by consuming other organisms" }],
    gedStrategy: "Trace one arrow at a time and say the relationship aloud: 'energy moves from ___ to ___.'",
    checkpoint: "Which organism receives energy directly from grass?",
    questions: [q("Which organism receives energy directly from grass?", "Grasshopper", ["Hawk", "Sparrow", "Sun"], "The chain shows Grass → Grasshopper."), q("Which organism is the producer?", "Grass", ["Grasshopper", "Sparrow", "Hawk"], "Grass captures light energy through photosynthesis."), q("What do the arrows represent in this food chain?", "Direction of energy transfer", ["Organism size", "Population count", "Geographic movement only"], "The arrow direction shows energy transfer between feeding levels.")],
  },
  {
    title: "Categorize and Classify",
    description: "Group organisms or processes by consistent defining characteristics.",
    summary: "Classification uses shared criteria. A valid system applies the same rule consistently to every item.",
    objectives: ["Apply defining characteristics", "Distinguish ecological relationships", "Use consistent classification rules"],
    explanation: ["In biology, relationship categories are defined by who benefits, who is harmed, and how organisms interact.", "Choose a category from the evidence, not from superficial appearance."],
    visual: { type: "table", title: "Ecological relationship guide", headers: ["Relationship", "Organism A", "Organism B"], rows: [["Mutualism", "benefits", "benefits"], ["Parasitism", "benefits", "harmed"], ["Competition", "cost", "cost"], ["Predation", "predator benefits", "prey harmed"]] },
    keyTerms: [{ marker: "mutualism", text: "both organisms benefit" }, { marker: "parasitism", text: "one benefits while the host is harmed" }, { marker: "competition", text: "organisms use the same limited resource" }],
    gedStrategy: "Translate the description into benefit/harm signs first, then match the pattern to a category.",
    checkpoint: "A tick benefits while the mammal host is harmed. Which category matches?",
    questions: [q("A tick feeds on a mammal and harms it. What is the relationship?", "Parasitism", ["Mutualism", "Competition", "Commensalism"], "One organism benefits while the host is harmed, matching parasitism."), q("If both species benefit, what relationship is shown?", "Mutualism", ["Parasitism", "Predation", "Competition"], "Mutualism is defined by benefit to both organisms."), q("What makes a classification fair?", "Using the same rule for every item", ["Changing the rule for each item", "Using appearance only", "Ignoring defining traits"], "Consistent criteria are essential for meaningful classification.")],
  },
  {
    title: "Generalize",
    description: "Build broad statements from multiple observations without overclaiming.",
    summary: "A scientific generalization extends across several observations but remains limited to what the evidence supports.",
    objectives: ["Combine repeated observations", "Avoid absolute overgeneralization", "Judge scope of a conclusion"],
    explanation: ["Strong generalizations are broader than one observation but narrower than an unsupported universal statement.", "Watch for words such as always, never, all, and none. They demand very strong evidence."],
    visual: { type: "process", title: "Building a generalization", steps: ["Observation A", "Observation B", "Observation C", "Supported broad statement"] },
    keyTerms: [{ marker: "generalization", text: "broad statement supported by multiple observations" }, { marker: "scope", text: "how widely a statement applies" }],
    gedStrategy: "Prefer language such as 'tends to,' 'often,' or 'in the studied cases' when the evidence does not justify an absolute claim.",
    checkpoint: "Is 'every ecosystem has exactly five species' justified by observing three diverse ecosystems?",
    questions: [q("Which is the strongest generalization from several ecosystems that all contain interacting populations?", "Ecosystems include interacting populations", ["Every ecosystem has exactly five species", "All organisms are predators", "No ecosystem changes"], "The statement captures the shared pattern without adding unsupported absolutes."), q("Which word often signals an overgeneralization?", "Always", ["May", "Often", "Sometimes"], "'Always' requires evidence covering every relevant case."), q("A valid generalization should be…", "Broad but still supported by the observations", ["Broader than all evidence", "Based on one exception", "Unrelated to the data"], "The scope must match the evidence base.")],
  },
  {
    title: "Compare and Contrast",
    description: "Compare the same features across organisms, treatments, or data sets.",
    summary: "Fair comparisons use the same characteristic, unit, and time frame for both items.",
    objectives: ["Identify similarities", "Identify differences", "Control the basis of comparison"],
    explanation: ["A comparison is only meaningful when the same feature is examined for each item. If one species is compared by mass and another by speed, the comparison is invalid.", "Tables and Venn-style organizers help separate shared and unique traits."],
    visual: { type: "compare", title: "Example comparison", leftTitle: "Bird", rightTitle: "Bat", left: ["feathers", "lays eggs"], shared: ["wings", "vertebrate", "breathes air"], right: ["hair", "gives live birth"] },
    keyTerms: [{ marker: "compare", text: "identify similarities" }, { marker: "contrast", text: "identify differences" }],
    gedStrategy: "Name the comparison variable before evaluating the data: 'I am comparing ___ for both groups.'",
    checkpoint: "Would comparing bird mass with bat wing length be a fair same-variable comparison?",
    questions: [q("What makes a comparison most valid?", "Using the same characteristic for both groups", ["Using unrelated units", "Using different time periods", "Ignoring the measurement method"], "Both groups must be evaluated using the same characteristic."), q("Which trait is shared by birds and bats in the visual?", "Wings", ["Feathers", "Hair", "Lays eggs"], "Wings appear in the shared section."), q("Which word best describes finding differences?", "Contrast", ["Compare only", "Predict", "Measure"], "To contrast is to identify differences.")],
  },
  {
    title: "Relate Text and Visuals",
    description: "Combine information presented in prose with diagrams, tables, or graphs.",
    summary: "Text and visuals often divide the evidence between them; strong answers integrate both sources.",
    objectives: ["Identify what a visual adds to text", "Combine multiple representations", "Avoid relying on only one source when both are relevant"],
    explanation: ["A paragraph may explain function while a diagram shows structure. A complete interpretation combines both.", "When the question says 'according to the passage and figure,' evidence from both is expected."],
    visual: { type: "layers", title: "DNA representation", layers: [{ name: "Outer rails", detail: "Sugar-phosphate backbone" }, { name: "Inner rungs", detail: "Paired nitrogen bases" }, { name: "Overall structure", detail: "Double helix stores hereditary information" }] },
    keyTerms: [{ marker: "representation", text: "a way of showing scientific information" }, { marker: "integrate", text: "combine information from multiple sources" }],
    gedStrategy: "Make a two-column note: 'text says' and 'visual shows.' Then combine them into one answer.",
    checkpoint: "If the text describes heredity but the figure labels base pairs, where does the structural evidence come from?",
    questions: [q("If text explains DNA function and a figure labels base pairs, what should you do?", "Combine evidence from both sources", ["Use only the text", "Use only the figure", "Ignore the labels"], "The two sources provide complementary information."), q("What do the inner 'rungs' represent in the visual?", "Paired nitrogen bases", ["Cell membranes", "Amino acids", "Ribosomes"], "The layered visual identifies paired bases as the inner rungs."), q("Why are visuals important on GED Science?", "They can contain evidence not repeated in the text", ["They are only decoration", "They replace every passage", "They never include labels"], "GED items often distribute information across multiple formats.")],
  },
  {
    title: "Understand Content-Based Tools",
    description: "Use tools such as Punnett squares, pedigrees, keys, and models.",
    summary: "Science tools organize relationships so that patterns and probabilities can be inferred systematically.",
    objectives: ["Read a Punnett square", "Connect alleles to predicted offspring", "Interpret probabilities rather than guarantees"],
    explanation: ["A Punnett square lists possible allele combinations from two parents. Each cell represents a possible genotype under the model.", "A probability does not guarantee the exact outcome of a small number of births."],
    visual: { type: "table", title: "Punnett square: Pp × Pp", headers: ["", "P", "p"], rows: [["P", "PP", "Pp"], ["p", "Pp", "pp"]], caption: "Each interior cell is one equally represented possible genotype in this simplified cross." },
    keyTerms: [{ marker: "allele", text: "alternative form of a gene" }, { marker: "genotype", text: "allele combination an organism carries" }, { marker: "probability", text: "likelihood of an outcome" }],
    gedStrategy: "Count boxes only after identifying what each allele means and whether the question asks genotype or phenotype.",
    checkpoint: "How many of the four cells show pp?",
    questions: [q("What fraction of the Punnett-square cells are pp?", "1/4", ["1/2", "3/4", "4/4"], "One of four equally represented cells is pp."), q("How many cells contain at least one P allele?", "3", ["1", "2", "4"], "PP, Pp, and Pp each contain at least one P."), q("Does a 1/4 probability mean exactly one of every four children must have that genotype?", "No, probability does not guarantee a fixed sequence", ["Yes, always", "Only for plants", "Only if four children are born"], "Probability describes likelihood across repeated outcomes, not a required sequence.")],
  },
  {
    title: "Use Context Clues",
    description: "Infer unfamiliar science vocabulary from definitions, examples, contrasts, and word parts.",
    summary: "Context clues let you infer technical vocabulary without stopping the reasoning process.",
    objectives: ["Recognize definition clues", "Use examples and contrasts", "Use scientific prefixes and roots"],
    explanation: ["Writers often define a scientific term immediately after it, restate it with 'or,' or illustrate it with examples.", "Word parts can also help: bio relates to life, thermo to heat, geo to Earth, and photo to light."],
    visual: { type: "table", title: "Context clue types", headers: ["Type", "Signal", "Example"], rows: [["Definition", "is / means / or", "thermal energy, or heat energy"], ["Example", "such as", "metals such as iron and copper"], ["Contrast", "unlike / however", "unlike solids, gases…"], ["Word part", "prefix/root", "thermo = heat"]] },
    keyTerms: [{ marker: "context clue", text: "nearby information that helps determine meaning" }, { marker: "root", text: "meaningful word part" }],
    gedStrategy: "Substitute your inferred meaning back into the sentence. If the sentence still makes sense, the inference is more likely correct.",
    checkpoint: "In 'thermal energy, or heat energy,' what does 'or' signal?",
    questions: [q("'Thermal energy, or heat energy' uses which context clue?", "Direct definition or restatement", ["Unrelated example", "Contradiction", "No context clue"], "The phrase after 'or' restates the meaning."), q("What does the root 'bio' usually relate to?", "Life", ["Heat", "Earth", "Light"], "Bio- is a common root associated with life."), q("How can you check an inferred word meaning?", "Substitute it into the sentence and test the meaning", ["Ignore the sentence", "Choose the longest dictionary definition", "Look only at punctuation"], "Context-based inference should fit the surrounding sentence and passage.")],
  },
  {
    title: "Understand Scientific Evidence",
    description: "Judge whether observations and data support scientific explanations.",
    summary: "Strong scientific evidence is relevant, reliably collected, and connected logically to the claim it supports.",
    objectives: ["Distinguish evidence from opinion", "Judge relevance and reliability", "Recognize converging lines of evidence"],
    explanation: ["Scientific claims are strengthened when different forms of evidence point toward the same explanation.", "A single observation may be suggestive without being sufficient for a broad conclusion."],
    visual: { type: "evidence", title: "Homologous structures and ancestry", claim: "Several vertebrates share common ancestry.", evidence: ["Human arm, bat wing, and whale flipper contain a similar underlying bone pattern", "The structures serve different present-day functions"], reasoning: "A shared structural pattern across different functions is consistent with inheritance from a common ancestral structure." },
    keyTerms: [{ marker: "evidence", text: "observations or data used to evaluate a claim" }, { marker: "reliability", text: "consistency and dependability of evidence" }],
    gedStrategy: "For each answer choice, ask: 'Which specific data point or observation supports this?'",
    checkpoint: "Does structural similarity alone prove every detail of evolutionary history?",
    questions: [q("Why can similar limb-bone patterns support common ancestry?", "They are shared structural evidence across different species", ["They prove every species has the same function", "They show organisms never change", "They remove the need for other evidence"], "Shared structural patterns are evidence consistent with common ancestry."), q("Which is strongest evidence?", "Repeated measurements collected with a reliable method", ["A personal preference", "An unsupported statement", "A decorative diagram"], "Reliable, repeated observations provide stronger scientific support."), q("Why are multiple lines of evidence valuable?", "They can independently support the same explanation", ["They guarantee no uncertainty", "They eliminate the need for reasoning", "They make all claims true"], "Converging evidence increases confidence when independent observations align.")],
  },
  {
    title: "Make and Identify Inferences",
    description: "Use observations and scientific knowledge to infer what is likely true.",
    summary: "An inference goes beyond direct observation but remains anchored to evidence and established knowledge.",
    objectives: ["Separate observations from inferences", "Build logical evidence-based inferences", "Avoid unsupported assumptions"],
    explanation: ["An observation reports what was seen or measured. An inference explains or predicts based on that evidence.", "Good inferences use cautious language when evidence is limited."],
    visual: { type: "process", title: "Observation to inference", steps: ["Light-colored deer are less visible on pale sand", "Predators detect visible prey more easily", "Camouflage may increase survival"] },
    keyTerms: [{ marker: "observation", text: "directly measured or noticed information" }, { marker: "inference", text: "logical interpretation based on evidence" }],
    gedStrategy: "Ask whether the statement was directly measured. If not, it may be an inference or conclusion.",
    checkpoint: "Is 'the deer has light fur' an observation or inference?",
    questions: [q("Which statement is an inference?", "Camouflage may improve survival", ["The deer has light fur", "The sand is pale", "The deer is on the sand"], "Survival benefit is inferred by combining visibility evidence with knowledge about predation."), q("Which is a direct observation?", "The measured population was 42 animals", ["The habitat must be ideal", "Predators caused every death", "The population will double"], "A measured count is directly observed data."), q("A strong inference should be…", "Closely supported by evidence", ["Independent of all evidence", "More certain than the data allow", "Based only on preference"], "Inference quality depends on its logical connection to observations.")],
  },
  {
    title: "Draw Conclusions",
    description: "Synthesize evidence and reasoning into a defensible final statement.",
    summary: "A scientific conclusion answers the question, fits the evidence, and respects the investigation's limits.",
    objectives: ["Connect conclusion to evidence", "Recognize limitations", "Avoid introducing untested causes"],
    explanation: ["A conclusion should not claim more than the experiment or data actually tested.", "When evidence is mixed, acknowledge uncertainty rather than hiding conflicting results."],
    visual: { type: "process", title: "Conclusion quality check", steps: ["Answer the question", "Cite relevant evidence", "Explain the connection", "State important limitations"] },
    keyTerms: [{ marker: "conclusion", text: "evidence-based final interpretation" }, { marker: "limitation", text: "factor that restricts what can be inferred" }],
    gedStrategy: "Eliminate answer choices that introduce a cause, population, condition, or certainty level never tested.",
    checkpoint: "If an experiment tested one temperature, can it justify claims about every possible temperature?",
    questions: [q("Which conclusion is strongest?", "One that directly follows from the collected evidence", ["One that adds an untested cause", "One based on preference", "One that ignores conflicting data"], "A defensible conclusion stays within the evidence."), q("Why mention limitations?", "They show what the evidence cannot establish confidently", ["To invalidate all results", "To make the conclusion longer", "To avoid using data"], "Limitations define the appropriate scope of inference."), q("What should you do with conflicting evidence?", "Consider it when judging the conclusion", ["Delete it automatically", "Ignore it", "Replace it with opinion"], "Scientific reasoning accounts for relevant conflicting results.")],
  },
];

const physicalScience: GedScienceV2LessonSeed[] = [
  {
    title: "Understand Scientific Models",
    description: "Use simplified representations to understand systems and make predictions.",
    summary: "Models highlight important features of a system while simplifying details that are not essential to the question.",
    objectives: ["Identify model components", "Recognize model limitations", "Use models to explain or predict"],
    explanation: ["Models can be physical, diagrammatic, mathematical, or computational. No model reproduces every feature of reality.", "A useful model makes relevant relationships easier to examine."],
    visual: { type: "layers", title: "Simple atomic model", layers: [{ name: "Nucleus", detail: "Contains protons (+) and neutrons (0)" }, { name: "Electron region", detail: "Contains negatively charged electrons" }, { name: "Model limitation", detail: "Not drawn to literal scale and simplifies electron behavior" }] },
    keyTerms: [{ marker: "model", text: "simplified representation of a system" }, { marker: "limitation", text: "way a model differs from reality" }],
    gedStrategy: "Use only relationships the model is designed to represent; do not infer unsupported scale or shape details.",
    checkpoint: "Does a ball-and-stick atom drawing show literal electron or nucleus sizes?",
    questions: [q("What is a major purpose of a scientific model?", "Represent and explain important features of a system", ["Reproduce every detail exactly", "Eliminate the need for evidence", "Show only visible objects"], "Models simplify systems to make key relationships understandable."), q("Where are protons located in this model?", "In the nucleus", ["In the electron region", "Outside the atom", "Only in molecules"], "The nucleus contains protons and neutrons."), q("Why should model limitations be considered?", "Because a model simplifies reality", ["Because models are never useful", "Because diagrams cannot contain evidence", "Because all models are identical"], "A model is a purposeful simplification, so not every depicted feature should be treated literally.")],
  },
  {
    title: "Interpret Complex Visuals",
    description: "Combine multiple labels, symbols, and relationships in one visual.",
    summary: "Complex visuals should be decomposed into smaller information layers before being interpreted as a whole.",
    objectives: ["Read legends and subparts", "Compare particle arrangements", "Connect microscopic patterns to macroscopic properties"],
    explanation: ["Particle diagrams commonly represent solids as tightly ordered particles, liquids as close but mobile particles, and gases as widely spaced particles.", "Focus on the feature being compared—spacing, arrangement, or motion—rather than decorative differences."],
    visual: { type: "table", title: "Particle model of matter", headers: ["State", "Spacing", "Arrangement", "Motion"], rows: [["Solid", "very close", "ordered", "vibrate in place"], ["Liquid", "close", "less ordered", "slide past one another"], ["Gas", "far apart", "disordered", "rapid free motion"]] },
    keyTerms: [{ marker: "particle", text: "small unit used in a matter model" }, { marker: "state", text: "physical form such as solid, liquid, or gas" }],
    gedStrategy: "When a visual contains many features, identify the exact variable named in the question and ignore unrelated detail.",
    checkpoint: "Which state has particles farthest apart?",
    questions: [q("Which state generally has particles farthest apart?", "Gas", ["Solid", "Liquid", "All are equal"], "Gas particles are modeled as widely separated."), q("Which state has a fixed ordered arrangement in the model?", "Solid", ["Liquid", "Gas", "All states"], "Solid particles are shown in an ordered arrangement."), q("Why divide a complex visual into subparts?", "To interpret each information layer accurately", ["To avoid reading labels", "To change the data", "To ignore relationships"], "Breaking the visual down reduces confusion and supports accurate integration.")],
  },
  {
    title: "Interpret Complex Tables",
    description: "Compare multiple variables, units, and conditions in a data table.",
    summary: "Complex tables require controlled comparisons: same variable, same unit, relevant rows, and awareness of confounding factors.",
    objectives: ["Compare compatible data", "Identify multiple variables", "Distinguish correlation from causation"],
    explanation: ["A table can show an association between variables without proving that one caused the other.", "Before comparing, confirm that the values come from compatible conditions and use the same units."],
    visual: { type: "table", title: "Sample substance properties", headers: ["Substance", "Bond type", "Boiling point (°C)", "Conducts as solid?"], rows: [["A", "ionic", "1413", "no"], ["B", "covalent", "80", "no"], ["C", "metallic", "2562", "yes"]] },
    keyTerms: [{ marker: "variable", text: "a characteristic that can differ or change" }, { marker: "correlation", text: "association between variables" }],
    gedStrategy: "State the comparison in a sentence including the unit before calculating or choosing an answer.",
    checkpoint: "Which substance in the table has the highest boiling point?",
    questions: [q("Which substance has the highest listed boiling point?", "C", ["A", "B", "A and B are tied"], "2562 °C is the largest value in the boiling-point column."), q("Which substance conducts electricity as a solid?", "C", ["A", "B", "All three"], "Only C is marked 'yes' in that column."), q("Does this table alone prove bond type causes boiling point differences?", "No, it shows an association but not a controlled causal test", ["Yes, automatically", "Only because the values are numbers", "Yes, if there are three rows"], "Causal conclusions require stronger experimental control than a descriptive table alone.")],
  },
  {
    title: "Understand Chemical Equations",
    description: "Read reactants, products, coefficients, and conservation relationships.",
    summary: "Balanced chemical equations represent conservation of atoms: each element has the same atom count before and after the reaction.",
    objectives: ["Identify reactants and products", "Count atoms", "Distinguish coefficients from subscripts"],
    explanation: ["Reactants appear to the left of the arrow and products to the right. Coefficients multiply whole formulas; subscripts are part of the chemical formula itself.", "Balancing changes coefficients, not chemical identities."],
    visual: { type: "formula", title: "Balanced magnesium reaction", formula: "2Mg + O₂ → 2MgO", variables: [{ marker: "2Mg", text: "2 magnesium atoms" }, { marker: "O₂", text: "2 oxygen atoms in one oxygen molecule" }, { marker: "2MgO", text: "2 formula units of magnesium oxide" }], example: "Left side: Mg = 2, O = 2. Right side: Mg = 2, O = 2." },
    keyTerms: [{ marker: "reactant", text: "starting substance" }, { marker: "product", text: "substance formed" }, { marker: "coefficient", text: "number multiplying a formula" }],
    gedStrategy: "Make a quick atom-count table for each element. If counts differ, the equation is not balanced.",
    checkpoint: "How many oxygen atoms are represented on each side of the equation?",
    questions: [q("Why must a chemical equation be balanced?", "To represent conservation of atoms and mass", ["To make every coefficient 1", "To remove all reactants", "To change element identities"], "Balancing ensures equal counts of each element on both sides."), q("Which substances are the reactants?", "Mg and O₂", ["MgO only", "Mg and MgO", "O₂ and MgO"], "Reactants are written to the left of the arrow."), q("What does the coefficient 2 before MgO mean?", "Two formula units of MgO", ["Two oxygen atoms inside one MgO", "MgO has atomic number 2", "Two different products"], "A coefficient multiplies the entire formula unit.")],
  },
  {
    title: "Predict Outcomes",
    description: "Use scientific patterns and conditions to predict likely results.",
    summary: "Predictions are evidence-based statements about unobserved outcomes under specified conditions.",
    objectives: ["Identify relevant conditions", "Extend patterns carefully", "Distinguish prediction from certainty"],
    explanation: ["A prediction should follow from the conditions and scientific principles given in the problem.", "For solutions, saturation means the solvent cannot dissolve additional solute under the same conditions."],
    visual: { type: "process", title: "Adding solute", steps: ["Unsaturated solution", "Add solute", "More dissolves", "At saturation", "Extra solute remains undissolved"] },
    keyTerms: [{ marker: "prediction", text: "expected outcome based on evidence" }, { marker: "saturated", text: "containing the maximum dissolved solute under given conditions" }],
    gedStrategy: "List the conditions that are held constant before predicting. A changed condition can change the outcome.",
    checkpoint: "What happens if more solute is added after saturation at the same temperature?",
    questions: [q("What is most likely after adding more solute to a saturated solution at the same temperature?", "Some added solute remains undissolved", ["All must dissolve", "The solvent disappears", "Temperature automatically doubles"], "At saturation, additional solute cannot fully dissolve under unchanged conditions."), q("A prediction should be based on…", "Observed patterns and scientific principles", ["Personal preference", "Answer-choice length", "Unrelated facts"], "Scientific predictions extend evidence and principles to likely outcomes."), q("Why do conditions matter in predictions?", "Changing conditions can change the outcome", ["Conditions never matter", "Only labels matter", "Predictions are always certain"], "Scientific relationships often depend on temperature, pressure, concentration, or other conditions.")],
  },
  {
    title: "Calculate to Interpret Outcomes",
    description: "Use formulas, units, and proportional reasoning to interpret measurements.",
    summary: "Calculation is a reasoning tool: choose the correct relationship, substitute values with units, and judge whether the result is reasonable.",
    objectives: ["Calculate average speed", "Track units", "Distinguish speed from velocity and displacement"],
    explanation: ["Average speed equals total distance divided by total time. Velocity includes direction, while speed does not.", "Always write the unit with the result; it is part of the scientific meaning."],
    visual: { type: "formula", title: "Average speed", formula: "speed = distance ÷ time", variables: [{ marker: "distance", text: "total path traveled" }, { marker: "time", text: "elapsed duration" }], example: "60 km ÷ 3 h = 20 km/h" },
    keyTerms: [{ marker: "speed", text: "distance traveled per unit time" }, { marker: "velocity", text: "speed with direction" }, { marker: "displacement", text: "straight-line change in position" }],
    gedStrategy: "Estimate before calculating. If 60 km takes 3 hours, the answer must be less than 60 km/h and around 20 km/h.",
    checkpoint: "A traveler moves 60 km in 3 h. What is the average speed?",
    questions: [q("A traveler moves 60 km in 3 h. What is the average speed?", "20 km/h", ["10 km/h", "30 km/h", "180 km/h"], "60 ÷ 3 = 20 km/h."), q("Which quantity includes direction?", "Velocity", ["Speed", "Distance", "Time"], "Velocity is a vector quantity with magnitude and direction."), q("Why include units in a calculation?", "They identify what the numerical result measures", ["They are decorative", "They always cancel completely", "They replace the formula"], "A value without the proper unit can be scientifically ambiguous.")],
  },
  {
    title: "Understand Vector Diagrams",
    description: "Use vector arrows to reason about magnitude, direction, and net force.",
    summary: "Vectors combine magnitude and direction. Net force is the vector sum of all forces acting on an object.",
    objectives: ["Read arrow direction", "Compare vector magnitude", "Calculate net force in one dimension"],
    explanation: ["Opposite vectors subtract; vectors in the same direction add. The direction of the net vector follows the larger contribution when opposite forces are unequal.", "Arrow length may represent magnitude if the diagram uses a scale."],
    visual: { type: "formula", title: "Opposing forces", formula: "12 N right − 4 N left = 8 N right", variables: [{ marker: "N", text: "newton, unit of force" }, { marker: "direction", text: "part of every vector quantity" }] },
    keyTerms: [{ marker: "vector", text: "quantity with magnitude and direction" }, { marker: "net force", text: "vector sum of forces" }],
    gedStrategy: "Choose a positive direction, attach signs to forces, then add. Translate the sign back into a direction at the end.",
    checkpoint: "What is the net force if 12 N acts right and 4 N acts left?",
    questions: [q("A box has 12 N right and 4 N left. What is the net force?", "8 N to the right", ["16 N to the right", "8 N to the left", "0 N"], "Opposing forces subtract: 12 − 4 = 8 N toward the larger force."), q("If two equal forces act in opposite directions, the net force is…", "0 N", ["Twice either force", "Always rightward", "Always leftward"], "Equal opposite vectors cancel."), q("What information does a vector require?", "Magnitude and direction", ["Magnitude only", "Color and shape", "Mass and temperature"], "Direction distinguishes vectors from scalar quantities.")],
  },
  {
    title: "Apply Scientific Laws",
    description: "Use established relationships such as Newton's laws, gravity, and conservation.",
    summary: "Scientific laws describe consistent relationships that can be applied when the problem conditions match.",
    objectives: ["Apply qualitative gravity relationships", "Connect force, mass, and acceleration", "Recognize conservation principles"],
    explanation: ["Gravitational attraction increases with mass and decreases with increasing distance.", "Newton's second law links net force, mass, and acceleration: greater net force produces greater acceleration for the same mass."],
    visual: { type: "formula", title: "Newton's second law", formula: "F = m × a", variables: [{ marker: "F", text: "net force (N)" }, { marker: "m", text: "mass (kg)" }, { marker: "a", text: "acceleration (m/s²)" }], example: "For the same mass, doubling net force doubles acceleration." },
    keyTerms: [{ marker: "law", text: "description of a consistent natural relationship" }, { marker: "conservation", text: "principle that a quantity remains accounted for in a closed system" }],
    gedStrategy: "Identify which variables change and which remain constant before applying a law.",
    checkpoint: "If distance between two masses increases, what happens to gravitational attraction?",
    questions: [q("If distance between two masses increases while masses stay the same, gravity becomes…", "Weaker", ["Stronger", "Exactly zero immediately", "Unrelated to distance"], "Gravitational attraction decreases as distance increases."), q("For the same mass, increasing net force causes…", "Greater acceleration", ["Less acceleration", "No change", "Less mass automatically"], "F = ma shows acceleration increases with force when mass is constant."), q("A conservation law means…", "A conserved quantity remains accounted for in the system", ["The quantity disappears", "Every variable stays constant", "No energy transfers occur"], "Conservation tracks a quantity through transformations and transfers.")],
  },
  {
    title: "Access Prior Knowledge",
    description: "Activate relevant science knowledge while keeping the provided evidence authoritative.",
    summary: "Prior knowledge helps interpret new contexts, but it should support—not replace—the evidence given in the question.",
    objectives: ["Recall relevant concepts", "Connect familiar and unfamiliar contexts", "Avoid overriding provided data with assumptions"],
    explanation: ["Simple machines such as levers can change the size or direction of an applied force by trading force for distance.", "Use prior knowledge to interpret the diagram, then rely on the actual labels and values shown."],
    visual: { type: "process", title: "Lever relationship", steps: ["Input force", "Lever arm", "Fulcrum", "Output force"] },
    keyTerms: [{ marker: "fulcrum", text: "pivot point of a lever" }, { marker: "mechanical advantage", text: "ratio describing force multiplication" }],
    gedStrategy: "Ask 'what concept does this remind me of?' but verify every recalled rule against the problem's actual conditions.",
    checkpoint: "What is the pivot point of a lever called?",
    questions: [q("What is the pivot point of a lever called?", "Fulcrum", ["Voltage", "Solute", "Nucleus"], "The fulcrum is the pivot about which a lever rotates."), q("What is a benefit of prior knowledge?", "It helps connect new information to known concepts", ["It lets you ignore the stimulus", "It guarantees your first answer", "It replaces measurement"], "Relevant prior knowledge can guide interpretation but does not replace evidence."), q("If the provided data contradict a remembered example, what should you use?", "The provided data for that question", ["The remembered example only", "Whichever answer is longer", "Neither source"], "GED reasoning is grounded in the evidence presented in the item.")],
  },
  {
    title: "Link Microscopic and Observable Events",
    description: "Connect particle-level behavior with measurable changes in matter.",
    summary: "Macroscopic properties such as temperature and phase can be explained using particle motion and arrangement.",
    objectives: ["Connect temperature to average kinetic energy", "Explain phase changes with particle models", "Distinguish particle identity from particle motion"],
    explanation: ["Temperature is related to the average kinetic energy of particles. Heating generally increases average particle motion.", "A phase change changes arrangement and energy, not the identity of each molecule."],
    visual: { type: "compare", title: "Particle motion", leftTitle: "Cooler sample", rightTitle: "Warmer sample", left: ["lower average kinetic energy", "slower average motion"], shared: ["same substance", "same particle identity"], right: ["higher average kinetic energy", "faster average motion"] },
    keyTerms: [{ marker: "kinetic energy", text: "energy of motion" }, { marker: "temperature", text: "measure related to average particle kinetic energy" }],
    gedStrategy: "When a visible property changes, ask what particle-level quantity could explain that change.",
    checkpoint: "What generally increases at the particle level when temperature rises?",
    questions: [q("What generally increases when temperature rises?", "Average particle kinetic energy", ["Atomic number", "Number of protons", "Element identity"], "Higher temperature corresponds to greater average kinetic energy."), q("During a physical phase change, do molecules become a new element?", "No, particle identity can remain the same", ["Yes, always", "Only during melting", "Only for gases"], "Physical changes alter arrangement and energy without necessarily changing chemical identity."), q("Which sample has faster average particle motion?", "The warmer sample", ["The cooler sample", "Both must be identical", "Temperature gives no information"], "The particle model links higher temperature with greater average kinetic energy.")],
  },
  {
    title: "Interpret Observations",
    description: "Separate measured observations from explanatory interpretations.",
    summary: "Observations report what happened; interpretations explain what the observations mean.",
    objectives: ["Identify direct measurements", "Distinguish interpretation from observation", "Connect evidence to energy changes"],
    explanation: ["A recorded speed, temperature, position, or mass is an observation. Statements about why the value changed are interpretations unless directly tested.", "Energy transformations can be inferred from systematic changes in motion and position."],
    visual: { type: "process", title: "Roller-coaster energy", steps: ["High position: more gravitational potential energy", "Descending", "Speed increases", "More kinetic energy"] },
    keyTerms: [{ marker: "observation", text: "direct measurement or recorded event" }, { marker: "interpretation", text: "explanation of what evidence means" }],
    gedStrategy: "Underline measured quantities. Treat explanatory language such as 'because' or 'therefore' as reasoning that must be supported.",
    checkpoint: "Is 'speed increased from 2 m/s to 5 m/s' an observation or interpretation?",
    questions: [q("Which statement is an observation?", "The measured speed increased from 2 m/s to 5 m/s", ["The object wanted to move faster", "Energy was destroyed", "An invisible cause must be responsible"], "The statement reports measured values directly."), q("As an object descends and speeds up, what energy generally increases?", "Kinetic energy", ["Gravitational potential energy", "Atomic energy", "Mass"], "Greater speed corresponds to more kinetic energy."), q("An interpretation should be…", "Supported by observations", ["Independent of data", "Based only on preference", "Automatically accepted"], "Interpretations are scientific only when evidence supports them.")],
  },
  {
    title: "Link Content from Varied Formats",
    description: "Integrate prose, graphs, equations, and diagrams representing the same concept.",
    summary: "Different formats can encode the same relationship; translating them into common language helps connect the evidence.",
    objectives: ["Translate diagrams into words", "Connect wave terms to visual features", "Combine formulas and graphs"],
    explanation: ["For waves, amplitude measures maximum displacement from equilibrium and wavelength measures the distance between corresponding points on successive waves.", "A graph, formula, and text description may each reveal different aspects of the same relationship."],
    visual: { type: "table", title: "Wave features", headers: ["Feature", "Meaning"], rows: [["Amplitude", "Maximum displacement from equilibrium"], ["Wavelength", "Distance between matching points on successive waves"], ["Frequency", "Number of cycles per unit time"]] },
    keyTerms: [{ marker: "amplitude", text: "maximum displacement" }, { marker: "wavelength", text: "distance between corresponding wave points" }, { marker: "frequency", text: "cycles per time" }],
    gedStrategy: "Translate every format into a sentence before combining them. For example: 'higher point = larger value.'",
    checkpoint: "What does wavelength measure?",
    questions: [q("What is wavelength?", "Distance between matching points on successive waves", ["The height of one particle", "The number of atoms", "The wave's temperature"], "Wavelength is the spatial period of a wave."), q("What does amplitude measure?", "Maximum displacement from equilibrium", ["Distance between crests", "Cycles per second", "Travel time"], "Amplitude is measured from equilibrium to a peak or trough."), q("Why translate formats into words?", "It makes relationships easier to integrate", ["It changes the data", "It removes units", "It makes visuals unnecessary"], "A common verbal representation helps connect graphs, diagrams, and equations.")],
  },
  {
    title: "Draw Conclusions from Mixed Sources",
    description: "Synthesize multiple passages, graphs, tables, and diagrams.",
    summary: "A mixed-source conclusion must fit all relevant evidence, not just one convenient source.",
    objectives: ["Combine evidence across sources", "Recognize conflicting evidence", "Avoid causal overclaims from correlation"],
    explanation: ["One source may describe a policy while another shows a pollution trend. Together they can support an association, but cause still requires careful reasoning.", "The strongest answer is compatible with all high-quality evidence provided."],
    visual: { type: "evidence", title: "Mixed-source reasoning", claim: "Pollution decreased after a policy change.", evidence: ["Passage: emissions policy changed in Year 1", "Graph: pollutant concentration declined over Years 1–4", "Table: several pollutants were tracked"], reasoning: "The sources support a temporal association. Additional controls would be needed to establish that the policy alone caused the decline." },
    keyTerms: [{ marker: "mixed sources", text: "multiple information formats or documents used together" }, { marker: "association", text: "relationship between observations without automatic proof of cause" }],
    gedStrategy: "Write one short evidence statement per source, then ask which answer choice fits all of them simultaneously.",
    checkpoint: "Does a decline after a policy change prove the policy was the only cause?",
    questions: [q("What should a mixed-source conclusion do?", "Fit the relevant evidence across the sources", ["Use only the most colorful source", "Ignore units", "Claim cause whenever trends coincide"], "A sound synthesis is compatible with all relevant evidence."), q("What does the evidence most directly show?", "Pollution declined after the policy change", ["The policy was definitely the only cause", "Pollution never changes naturally", "No other variables matter"], "Temporal association is directly supported; exclusive causation is not."), q("Why examine every source?", "Each may provide a different piece of the evidence", ["Only to increase reading time", "Because one source is always wrong", "To avoid using graphs"], "Mixed-source items distribute information across multiple representations.")],
  },
  {
    title: "Understand Investigation Techniques",
    description: "Identify hypotheses, variables, controls, procedures, and replication.",
    summary: "Controlled investigations change an independent variable and measure a dependent variable while controlling other important conditions.",
    objectives: ["Identify independent and dependent variables", "Recognize controls and constants", "Explain why repeated trials improve reliability"],
    explanation: ["The independent variable is deliberately changed. The dependent variable is the measured response.", "Constants and control conditions help isolate the relationship being tested."],
    visual: { type: "table", title: "Investigation design", headers: ["Element", "Role"], rows: [["Independent variable", "intentionally changed"], ["Dependent variable", "measured response"], ["Constants", "kept the same"], ["Control", "comparison condition"], ["Repeated trials", "test consistency"]] },
    keyTerms: [{ marker: "hypothesis", text: "testable proposed explanation or prediction" }, { marker: "control", text: "comparison condition" }, { marker: "replication", text: "repetition used to assess reliability" }],
    gedStrategy: "Turn the experiment into: 'The scientist changed ___ and measured ___ while keeping ___ constant.'",
    checkpoint: "If applied force is changed and acceleration measured, which variable is independent?",
    questions: [q("A researcher changes applied force and measures acceleration. What is the independent variable?", "Applied force", ["Acceleration", "The data table", "The conclusion"], "The independent variable is intentionally changed."), q("What is the dependent variable?", "Acceleration", ["Applied force", "The control group", "The hypothesis"], "Acceleration is the measured response."), q("Why repeat trials?", "To assess consistency and improve reliability", ["To guarantee the hypothesis", "To change multiple variables", "To remove all uncertainty"], "Replication helps determine whether results are reproducible.")],
  },
  {
    title: "Evaluate Scientific Information",
    description: "Judge validity, reliability, source quality, and whether conclusions match evidence.",
    summary: "Evaluation asks whether the method can test the claim, whether the data are trustworthy, and whether the conclusion stays within the results.",
    objectives: ["Evaluate study design", "Recognize bias and uncontrolled variables", "Judge whether evidence supports a conclusion"],
    explanation: ["A testable hypothesis, appropriate measurements, fair comparison, and replication strengthen a study.", "Large claims require evidence with appropriate scope and quality."],
    visual: { type: "process", title: "Scientific information quality check", steps: ["Testable question", "Appropriate method", "Reliable measurements", "Replicated pattern", "Evidence-based conclusion"] },
    keyTerms: [{ marker: "validity", text: "whether a method appropriately tests the intended question" }, { marker: "reliability", text: "whether results are consistent" }, { marker: "bias", text: "systematic influence that can distort results" }],
    gedStrategy: "Look for the weakest link: uncontrolled variable, tiny sample, inconsistent method, missing control, or conclusion broader than the data.",
    checkpoint: "Which change usually increases confidence in a result: repetition or deleting inconvenient measurements?",
    questions: [q("Which change most improves confidence in an experimental result?", "Repeating the investigation and obtaining consistent results", ["Removing disagreeing measurements", "Changing several variables at once", "Choosing the conclusion first"], "Consistent replication strengthens reliability."), q("What threatens validity?", "Changing multiple important variables at once", ["Using a control", "Measuring the dependent variable", "Repeating trials"], "If several variables change, the cause of the response becomes harder to isolate."), q("A conclusion should match…", "The scope and quality of the evidence", ["The researcher's preference", "The longest answer choice", "A claim made before data collection"], "Scientific conclusions must be proportional to the evidence.")],
  },
];

const earthSpace: GedScienceV2LessonSeed[] = [
  {
    title: "Understand Scientific Theories",
    description: "Distinguish well-supported scientific theories from guesses and connect them to evidence.",
    summary: "A scientific theory is a broad, well-supported explanation that integrates many observations and can be refined with new evidence.",
    objectives: ["Define scientific theory", "Connect theory to evidence", "Distinguish theories from laws and guesses"],
    explanation: ["Theories explain why patterns occur; laws commonly describe consistent relationships. Neither means a casual guess in science.", "The Big Bang model is supported by multiple lines of evidence, including cosmic expansion and background radiation."],
    visual: { type: "evidence", title: "Evidence for an expanding universe", claim: "The universe has expanded from a hotter, denser early state.", evidence: ["Distant galaxies show systematic redshift", "Cosmic microwave background radiation is observed", "Observed light-element abundances match model predictions"], reasoning: "Independent observations are consistent with predictions of the Big Bang model." },
    keyTerms: [{ marker: "theory", text: "well-supported explanatory framework" }, { marker: "law", text: "description of a consistent natural relationship" }, { marker: "redshift", text: "shift of light toward longer wavelengths, often indicating recession" }],
    gedStrategy: "Do not reject an answer because it says 'theory.' In science, theory means evidence-supported explanation, not guess.",
    checkpoint: "Which is stronger scientific language: 'unsupported guess' or 'well-supported explanation'?",
    questions: [q("Which best describes a scientific theory?", "A well-supported explanation of natural phenomena", ["An unsupported guess", "A rule that can never change", "A personal opinion"], "Scientific theories integrate substantial evidence into explanatory frameworks."), q("Which observation supports cosmic expansion?", "Systematic redshift of distant galaxies", ["Cloud formation", "Daily tides only", "Earth's seasons"], "Galaxy redshift is a major observational line of evidence for expansion."), q("Can a scientific theory be refined?", "Yes, when new evidence supports refinement", ["No, never", "Only by voting", "Only if it becomes a law"], "Scientific explanations can be updated as evidence improves.")],
  },
  {
    title: "Summarize Complex Material",
    description: "Condense dense scientific text while preserving central ideas and relationships.",
    summary: "A strong summary keeps the main idea and essential supporting relationships while omitting minor detail.",
    objectives: ["Identify essential ideas", "Paraphrase accurately", "Avoid including unsupported detail"],
    explanation: ["Summaries should be shorter than the source and written in your own words while preserving scientific meaning.", "For systems such as the Sun, focus on the energy source and major structural pathway rather than every example."],
    visual: { type: "layers", title: "Sun structure — summary", layers: [{ name: "Core", detail: "Nuclear fusion releases energy" }, { name: "Radiative/convective regions", detail: "Energy moves outward" }, { name: "Photosphere", detail: "Visible surface" }, { name: "Corona", detail: "Outer atmosphere" }] },
    keyTerms: [{ marker: "summary", text: "concise statement of central information" }, { marker: "fusion", text: "joining light nuclei while releasing energy" }],
    gedStrategy: "For each detail ask: would the main explanation become misleading if this detail were removed? If not, it may be minor.",
    checkpoint: "Which idea is essential in a summary of how the Sun produces energy?",
    questions: [q("Which detail is most important in a summary of how the Sun produces energy?", "Nuclear fusion occurs in the core", ["One sunspot has a particular shape", "A diagram uses yellow", "The page has a title"], "Fusion in the core is central to the explanation of solar energy production."), q("A good summary should be…", "Accurate and concise", ["Longer than the source", "Focused on minor examples", "Filled with new claims"], "Summaries preserve central meaning while reducing detail."), q("Where does solar fusion occur?", "The core", ["The corona", "The photosphere", "Earth's atmosphere"], "The visual identifies the core as the fusion region.")],
  },
  {
    title: "Understand Patterns in Science",
    description: "Recognize repeating spatial, temporal, and causal patterns and use them for prediction.",
    summary: "Patterns help scientists describe regularity and generate testable expectations about future observations.",
    objectives: ["Recognize repeating cycles", "Link rotation to day/night", "Use patterns without assuming they explain cause by themselves"],
    explanation: ["Earth's rotation creates the repeating day-night cycle. Other patterns, such as tides, involve gravitational relationships among Earth, Moon, and Sun.", "A pattern can motivate an explanation but does not automatically prove the mechanism."],
    visual: { type: "process", title: "Day-night cycle", steps: ["Earth rotates", "Location turns toward Sun", "Day", "Location rotates away", "Night", "Cycle repeats"] },
    keyTerms: [{ marker: "pattern", text: "repeated or systematic relationship" }, { marker: "rotation", text: "spinning around an axis" }, { marker: "cycle", text: "sequence that repeats" }],
    gedStrategy: "Identify what repeats, how often it repeats, and which variable changes with the cycle.",
    checkpoint: "What Earth motion directly produces the daily day-night cycle?",
    questions: [q("What causes the repeating day-night pattern?", "Earth's rotation", ["Earth's revolution alone", "Moon color changes", "Cloud formation"], "As Earth rotates, locations alternately face toward and away from the Sun."), q("A repeating pattern can be used to…", "Make evidence-based predictions", ["Guarantee a causal explanation", "Ignore new data", "Prove every mechanism"], "Regular patterns support predictions, though mechanisms require additional reasoning."), q("What is rotation?", "Spinning around an axis", ["Orbiting another body", "Moving in a straight line only", "Changing chemical composition"], "Rotation is spin about an axis.")],
  },
  {
    title: "Interpret Three-Dimensional Diagrams",
    description: "Use cutaways and layered diagrams to understand spatial structures.",
    summary: "Three-dimensional and cutaway diagrams reveal internal spatial relationships that cannot be seen from an exterior view.",
    objectives: ["Read nested layers", "Distinguish structure from scale", "Identify major Earth layers"],
    explanation: ["Earth diagrams commonly show crust, mantle, outer core, and inner core as nested regions.", "Unless a scale is provided, do not assume the drawing's thicknesses are proportional to real thicknesses."],
    visual: { type: "layers", title: "Earth cutaway", layers: [{ name: "Crust", detail: "Thin outer solid layer" }, { name: "Mantle", detail: "Thick rocky layer" }, { name: "Outer core", detail: "Liquid metal" }, { name: "Inner core", detail: "Solid metal" }], caption: "Nested boxes represent deeper layers; this is not a scale drawing." },
    keyTerms: [{ marker: "cutaway", text: "diagram showing internal structures" }, { marker: "scale", text: "relationship between drawing size and real size" }],
    gedStrategy: "Separate 'what is inside what' from 'how thick it really is.' Spatial order can be correct even when scale is stylized.",
    checkpoint: "Which major Earth layer is liquid?",
    questions: [q("Which Earth layer is liquid in the standard model?", "Outer core", ["Crust", "Mantle", "Inner core"], "The outer core is liquid, whereas the inner core is solid."), q("Which layer is outermost?", "Crust", ["Mantle", "Outer core", "Inner core"], "The crust is Earth's outermost major layer."), q("Why be cautious about thickness in a cutaway diagram?", "The drawing may not be to scale", ["Layers have no order", "Labels are always wrong", "The Earth has no internal structure"], "Stylized diagrams often preserve relationships without literal proportions.")],
  },
  {
    title: "Apply Science Concepts",
    description: "Transfer scientific principles to new Earth, environmental, and space contexts.",
    summary: "Application means recognizing the underlying principle even when the surface context changes.",
    objectives: ["Apply energy-flow concepts", "Apply energy-conversion concepts", "Recognize producers in ecological systems"],
    explanation: ["Marine food webs and terrestrial food webs share the same basic energy-flow principle: producers capture energy that then moves through consumers.", "Energy technologies such as tidal power transform motion into electrical energy through turbines and generators."],
    visual: { type: "process", title: "Tidal power conversion", steps: ["Moving water", "Turbine rotates", "Generator rotates", "Electrical energy"] },
    keyTerms: [{ marker: "producer", text: "organism that captures energy to build organic molecules" }, { marker: "energy conversion", text: "change from one energy form to another" }],
    gedStrategy: "Strip away the story context and name the principle: energy transfer, conservation, force, cycles, or systems interaction.",
    checkpoint: "In a food web, which organisms introduce new chemical energy through photosynthesis?",
    questions: [q("Which organisms bring new chemical energy into a food web through photosynthesis?", "Producers", ["Top predators", "All consumers equally", "Parasites only"], "Producers capture light energy and store it as chemical energy."), q("What is the first energy input in tidal generation?", "Motion of water", ["Nuclear fusion in the turbine", "Chemical energy in batteries only", "Sound energy"], "The turbine is driven by moving water."), q("Applying a concept means…", "Using the same underlying principle in a new context", ["Memorizing the story wording", "Ignoring scientific relationships", "Changing the law"], "Transfer requires recognizing the common principle beneath different scenarios.")],
  },
  {
    title: "Express Scientific Information",
    description: "Translate information among words, numbers, graphs, tables, and concise explanations.",
    summary: "Scientific communication should be accurate, labeled, proportional, and matched to the kind of data being presented.",
    objectives: ["Choose an appropriate display", "Label axes and units", "Translate percentages into visual comparisons"],
    explanation: ["Graphs need descriptive titles, labeled axes, and units when quantities are measured.", "Bar charts are useful for category comparisons; line graphs are useful for trends over ordered or continuous variables."],
    visual: { type: "bar", title: "Approximate composition of dry air", items: [{ label: "Nitrogen", value: 78, unit: "%" }, { label: "Oxygen", value: 21, unit: "%" }, { label: "Other gases", value: 1, unit: "%" }], caption: "Bar lengths correspond to approximate percentage values." },
    keyTerms: [{ marker: "axis", text: "reference line on a graph" }, { marker: "proportion", text: "relative amount or fraction" }],
    gedStrategy: "Choose the representation that makes the question's relationship easiest to see: categories → bars, trend over time → line, exact values → table.",
    checkpoint: "Which gas is most abundant in the displayed air composition?",
    questions: [q("Which gas is most abundant in the chart?", "Nitrogen", ["Oxygen", "Other gases", "All are equal"], "Nitrogen is shown at about 78%, the largest proportion."), q("Which graph feature is essential for a measured axis?", "A clear label and unit when applicable", ["Decorative clip art", "A hidden scale", "Unrelated colors"], "Axis labels and units define the quantitative meaning."), q("Which display is usually best for a trend over time?", "A line graph", ["A random icon list", "An unlabeled picture", "A paragraph with no values"], "Line graphs effectively show how a variable changes across ordered time points.")],
  },
  {
    title: "Identify Problem and Solution",
    description: "Recognize environmental or engineering problems and evaluate proposed responses.",
    summary: "A useful solution addresses the cause of a problem while considering effectiveness, feasibility, and trade-offs.",
    objectives: ["Identify the core problem", "Match solutions to causes", "Consider trade-offs"],
    explanation: ["Soil erosion removes topsoil by water or wind. Vegetation can reduce erosion because roots help stabilize soil and plant cover reduces direct impact of rain and wind.", "A solution should be evaluated by evidence, not by whether it sounds appealing."],
    visual: { type: "process", title: "Soil-erosion problem and response", steps: ["Bare soil", "Rain/wind removes particles", "Topsoil loss", "Plant vegetation", "Roots and cover reduce erosion"] },
    keyTerms: [{ marker: "erosion", text: "movement of weathered material" }, { marker: "trade-off", text: "cost or disadvantage that accompanies a benefit" }],
    gedStrategy: "Match each proposed solution to the mechanism causing the problem. Eliminate responses that would worsen the mechanism.",
    checkpoint: "Which action helps hold soil in place?",
    questions: [q("Which solution most directly helps reduce soil erosion?", "Planting vegetation", ["Removing roots", "Increasing bare soil", "Directing more runoff over the slope"], "Roots stabilize soil and vegetation cover reduces erosive forces."), q("A good solution should…", "Address the mechanism causing the problem", ["Ignore the cause", "Create the same problem more strongly", "Be chosen only by popularity"], "Mechanism-based solutions are more likely to be effective."), q("Why consider trade-offs?", "Solutions can have costs or side effects", ["Trade-offs make evidence unnecessary", "Every solution has only benefits", "Trade-offs are unrelated to decisions"], "Engineering and environmental decisions often balance multiple outcomes.")],
  },
  {
    title: "Analyze and Present Arguments",
    description: "Evaluate claims, evidence, reasoning, and trade-offs in scientific arguments.",
    summary: "A strong scientific argument links a clear claim to relevant evidence through explicit reasoning and addresses important counterevidence or trade-offs.",
    objectives: ["Identify claim, evidence, and reasoning", "Evaluate relevance of evidence", "Address counterpoints"],
    explanation: ["Evidence does not speak for itself; reasoning explains why the evidence supports the claim.", "Energy-policy arguments often require comparing emissions, reliability, cost, land use, and resource availability."],
    visual: { type: "evidence", title: "CER argument structure", claim: "A proposed energy source is appropriate for a community.", evidence: ["Low operational emissions", "Local resource availability", "Measured reliability", "Estimated cost"], reasoning: "The evidence must be weighted against community needs and trade-offs before the claim is justified." },
    keyTerms: [{ marker: "claim", text: "position or conclusion being argued" }, { marker: "evidence", text: "data or observations supporting the claim" }, { marker: "reasoning", text: "logical link between evidence and claim" }, { marker: "counterpoint", text: "relevant competing consideration" }],
    gedStrategy: "Label each sentence in an argument C, E, or R. If evidence is present without reasoning, ask how it actually supports the claim.",
    checkpoint: "Which part of an argument explains why the evidence matters?",
    questions: [q("Which component explains why evidence supports a claim?", "Reasoning", ["A label", "A page number", "A decorative image"], "Reasoning connects evidence logically to the claim."), q("Which is evidence in an energy argument?", "Measured reliability data", ["I like this technology", "It looks modern", "Everyone should agree"], "Measured performance data can directly support evaluation."), q("Why include a counterpoint?", "To address an important competing consideration or limitation", ["To avoid evidence", "To make the claim automatically true", "To remove all uncertainty"], "Acknowledging relevant trade-offs makes an argument more complete and defensible.")],
  },
];

export const gedScienceV2Course: OfficialLanguageQuestCourse = {
  code: "MRLC-GED-SCIENCE-V2",
  title: "GED Science V2",
  description: "A concept-first, visual, evidence-based GED Science course with rich learning blocks, labeled tables/diagrams, formulas, worked examples, checkpoints, and expanded practice before assessment.",
  language: "GED Science",
  category: "GED Preparation",
  imageEmoji: "",
  accentColor: "#0369a1",
  published: true,
  units: [
    { title: "Unit 1: Life Science", description: "Biological systems, evidence, visuals, and scientific reasoning.", lessons: lifeScience.map(lesson) },
    { title: "Unit 2: Physical Science", description: "Matter, motion, energy, equations, models, and experimental reasoning.", lessons: physicalScience.map(lesson) },
    { title: "Unit 3: Earth & Space Science", description: "Earth systems, astronomy, environmental science, and scientific argument.", lessons: earthSpace.map(lesson) },
  ],
};
