export interface VocabularyWord { word: string; meaning: string; example: string }
export interface WordLevel { id: string; title: string; letters: string; words: VocabularyWord[]; bonus: VocabularyWord[] }
export interface WordWorld { id: string; title: string; description: string; color: string; levels: WordLevel[] }

const word = (word: string, meaning: string, example: string): VocabularyWord => ({ word, meaning, example });
const level = (id: string, title: string, letters: string, words: VocabularyWord[], bonus: VocabularyWord[] = []): WordLevel => ({ id, title, letters, words, bonus });

export const WORLDS: WordWorld[] = [
  { id: 'school', title: 'The Reading Grove', description: 'Every adventure begins with a little curiosity.', color: '#168c83', levels: [
    level('read', 'A new chapter', 'READ', [word('READ', 'To look at written words and understand them.', 'I read a book after school.'), word('DEAR', 'Loved or valued; also used to begin a letter.', 'Dear Maya, thank you for your letter.'), word('DARE', 'To be brave enough to do something.', 'Do you dare to try a new activity?'), word('EAR', 'The part of your body that you hear with.', 'The music reached my ear.')], [word('RED', 'The colour of a ripe tomato.', 'Her bag is red.'), word('ARE', 'A form of the verb be, used with you, we, or they.', 'We are ready.')]),
    level('write', 'Letters from a friend', 'WRITE', [word('WRITE', 'To make words on paper or a screen.', 'Please write your name.'), word('WIRE', 'A thin piece of metal, often used to carry electricity.', 'The lamp has a loose wire.'), word('TIRE', 'To become tired, or make someone tired.', 'A long walk can tire you.'), word('TIE', 'To fasten something with a knot.', 'I can tie my shoes.')], [word('WET', 'Covered with water or another liquid.', 'My coat is wet.'), word('WIT', 'The ability to say clever or funny things.', 'Her wit made us laugh.')]),
    level('learn', 'Curiosity checkpoint', 'LEARN', [word('LEARN', 'To gain knowledge or a new skill.', 'We learn a new word each day.'), word('NEAR', 'Not far away.', 'The library is near my house.'), word('REAL', 'Existing; not imaginary.', 'That is a real butterfly.'), word('EAR', 'The part of your body that you hear with.', 'Cover one ear and listen.')], [word('RAN', 'The past tense of run.', 'He ran to the bus.'), word('LEAN', 'To move your body towards something.', 'Do not lean over the fence.')]),
  ] },
  { id: 'food', title: 'The Picnic Meadow', description: 'Gather fresh words for a very good picnic.', color: '#f2b84b', levels: [
    level('pear', 'Something sweet', 'PEAR', [word('PEAR', 'A sweet fruit with a narrow top and rounded bottom.', 'She ate a ripe pear.'), word('PARE', 'To remove the skin or outer layer of something.', 'Pare the apple before cooking it.'), word('EAR', 'The part of your body that you hear with.', 'A bee buzzed near my ear.')], [word('ARE', 'A form of the verb be, used with you, we, or they.', 'The pears are ripe.'), word('RAP', 'To knock quickly, or a style of music.', 'I heard a rap on the door.')]),
    level('plate', 'Set the table', 'PLATE', [word('PLATE', 'A flat dish that holds food.', 'Put the bread on a plate.'), word('PETAL', 'One of the colourful parts of a flower.', 'A pink petal fell onto the table.'), word('LATE', 'After the expected time.', 'We were late for the picnic.'), word('TEA', 'A drink made by putting tea leaves in hot water.', 'Would you like a cup of tea?')], [word('TALE', 'A story.', 'Grandma told us a funny tale.'), word('LEAP', 'To jump a long distance or high into the air.', 'The rabbit made a leap.')]),
    level('bread', 'The picnic basket', 'BREAD', [word('BREAD', 'Food made from flour and water, usually baked.', 'We shared a loaf of bread.'), word('BEARD', 'Hair growing on a person’s chin and cheeks.', 'My uncle has a short beard.'), word('READ', 'To understand written words.', 'Read the recipe first.'), word('BAD', 'Not good or unpleasant.', 'The weather was bad.')], [word('DEAR', 'Loved or valued.', 'She is a dear friend.'), word('BARE', 'Not covered.', 'The tree has bare branches.')]),
  ] },
  { id: 'travel', title: 'The Journey Junction', description: 'Pack your words. There is a world to explore.', color: '#4e91bd', levels: [
    level('train', 'All aboard', 'TRAIN', [word('TRAIN', 'Connected vehicles that travel along railway tracks.', 'We took the train to the city.'), word('RAIN', 'Water that falls from clouds.', 'The rain stopped before our trip.'), word('TIN', 'A metal, or a container made from metal.', 'We packed biscuits in a tin.'), word('ART', 'Creative work such as painting or drawing.', 'We saw beautiful art at the museum.')], [word('RAN', 'The past tense of run.', 'She ran to catch the train.'), word('ANT', 'A small insect that usually lives in a group.', 'An ant walked across the path.')]),
    level('plane', 'Above the clouds', 'PLANE', [word('PLANE', 'A vehicle that flies through the air.', 'The plane landed safely.'), word('PLAN', 'An idea about how to do something.', 'Our plan is to visit the coast.'), word('LANE', 'A narrow road or part of a larger road.', 'Ride your bicycle in the cycle lane.'), word('PEN', 'A tool used for writing with ink.', 'I brought a pen to write postcards.')], [word('LEAP', 'To jump.', 'The child made a leap over the puddle.'), word('PALE', 'Light in colour.', 'The sky was pale blue.')]),
    level('travel', 'A little further', 'TRAVEL', [word('TRAVEL', 'To go from one place to another.', 'I want to travel by train.'), word('LATER', 'At a time after now.', 'We will leave later.'), word('ALERT', 'Watching carefully and ready to act.', 'Stay alert when crossing a road.'), word('RATE', 'The speed or frequency at which something happens.', 'The train moved at a steady rate.')], [word('TEAR', 'A drop of liquid from the eye.', 'A tear rolled down his cheek.'), word('REAL', 'Existing; not imaginary.', 'The journey felt like a real adventure.')]),
  ] },
  { id: 'nature', title: 'The Wildwood', description: 'Discover the small wonders all around you.', color: '#6e9f76', levels: [
    level('leaf', 'Little green wonders', 'LEAF', [word('LEAF', 'A flat, usually green part of a plant.', 'A leaf floated down from the tree.'), word('FLEA', 'A tiny jumping insect that feeds on animals.', 'The dog had a flea.'), word('ELF', 'A small magical person in stories.', 'An elf lived in the forest story.')]),
    level('stone', 'By the river', 'STONE', [word('STONE', 'A small piece of rock.', 'He found a smooth stone by the river.'), word('NOTES', 'Short pieces of writing that help you remember.', 'I took notes about the birds.'), word('TONE', 'The quality of a sound or someone’s voice.', 'She spoke in a gentle tone.'), word('ONE', 'The number 1.', 'One bird sat on the branch.')], [word('NOTE', 'A short written message.', 'I left a note on the table.'), word('NEST', 'A home built by a bird for its eggs.', 'There is a nest in the tree.')]),
    level('forest', 'The explorer’s finish', 'FOREST', [word('FOREST', 'A large area covered with trees.', 'Many animals live in the forest.'), word('FROST', 'A thin layer of ice that forms in cold weather.', 'Frost covered the leaves.'), word('SOFT', 'Easy to press, bend, or touch comfortably.', 'The moss felt soft.'), word('REST', 'To stop working and relax.', 'We stopped to rest under a tree.')], [word('ROSE', 'A flower with many petals, often fragrant.', 'A rose grew beside the gate.'), word('TOES', 'The small parts at the end of your feet.', 'My toes were cold.')]),
  ] },
];

export const LEVELS = WORLDS.flatMap(world => world.levels);
export const worldFor = (levelId: string) => WORLDS.find(world => world.levels.some(level => level.id === levelId))!;
