-- Financial Modules: Fee Structures, Expense Management, Vendor Management,
-- Budgets, and Donation Tracking.
--
-- These models were added directly to schema.prisma (Expense, Vendor,
-- BillPayment, RecurringExpense, Budget, Donor, Donation, DonationCampaign,
-- DonationReceipt, FeeStructure, FeeItem, FeeAssignment, FeeDiscount,
-- FeePaymentPlan, FeeInstallment) along with two new nullable link columns on
-- the pre-existing FeePayment table (assignmentId, installmentId), but no
-- migration was ever generated for any of it. `prisma migrate status`
-- reported "up to date" while none of these tables/columns existed on the
-- live database, so every route under /api/expenses, /api/vendors,
-- /api/bill-payments, /api/recurring-expenses, /api/budgets, /api/donors,
-- /api/donations, /api/campaigns, /api/fee-structures, /api/fee-items,
-- /api/fee-assignments, /api/fee-discounts and /api/fee-payment-plans would
-- fail at runtime against a real database.
--
-- NON-DESTRUCTIVE: only adds new enums, tables, columns, and indexes; no
-- existing data is touched. Idempotent so it's safe to re-run.
--
-- IMPORTANT: generated by hand (not via `prisma migrate dev`) because this
-- sandbox cannot reach binaries.prisma.sh to download the schema-engine
-- binary. Written directly against the model definitions in schema.prisma.
-- Please run `npx prisma migrate status` / diff the live schema against this
-- file (e.g. `psql \d` on the affected tables) before applying in production,
-- per this repo's usual migration-safety practice.

-- ── Enums ────────────────────────────────────────────────────────────────────
DO $$ BEGIN CREATE TYPE "FeeStructureStatus" AS ENUM ('DRAFT','ACTIVE','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE "FeeFrequency" AS ENUM ('ONE_TIME','MONTHLY','TERMLY','YEARLY'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE "FeeDiscountType" AS ENUM ('PERCENTAGE','FIXED_AMOUNT','SIBLING_DISCOUNT','SCHOLARSHIP','EARLY_PAYMENT'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE "InstallmentStatus" AS ENUM ('PENDING','DUE','PAID','OVERDUE','WAIVED'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE "ExpenseStatus" AS ENUM ('DRAFT','PENDING_APPROVAL','APPROVED','PARTIAL','PAID','REJECTED','CANCELLED'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE "ExpenseCategory" AS ENUM ('OPERATIONAL','ACADEMIC','STAFF_COSTS','FOOD_CATERING','TRANSPORTATION','FACILITY','TECHNOLOGY','EVENT','ADMINISTRATIVE','OTHER'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE "PaymentMethod" AS ENUM ('CASH','BANK_TRANSFER','CHECK','CREDIT_CARD','DEBIT_CARD','ONLINE_PAYMENT','WIRE_TRANSFER','OTHER'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE "RecurringExpenseFrequency" AS ENUM ('DAILY','WEEKLY','BI_WEEKLY','MONTHLY','QUARTERLY','SEMI_ANNUALLY','ANNUALLY'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE "BudgetStatus" AS ENUM ('ACTIVE','EXHAUSTED','EXCEEDED','ARCHIVED'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE "DonationStatus" AS ENUM ('PENDING','RECEIVED','PROCESSED','CANCELLED','REFUNDED'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE "DonationType" AS ENUM ('ONE_TIME','RECURRING_MONTHLY','RECURRING_QUARTERLY','RECURRING_YEARLY','IN_KIND'); EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN CREATE TYPE "CampaignStatus" AS ENUM ('DRAFT','ACTIVE','PAUSED','COMPLETED','CANCELLED'); EXCEPTION WHEN duplicate_object THEN null; END $$;

-- ── Budget (created early: referenced by Expense, RecurringExpense, FeeItem) ─
CREATE TABLE IF NOT EXISTS "Budget" (
  "id"               TEXT NOT NULL,
  "name"             TEXT NOT NULL,
  "code"             TEXT,
  "description"      TEXT,
  "status"           "BudgetStatus" NOT NULL DEFAULT 'ACTIVE',
  "fiscalYear"       INTEGER NOT NULL,
  "startDate"        TIMESTAMP(3) NOT NULL,
  "endDate"          TIMESTAMP(3) NOT NULL,
  "allocatedAmount"  DOUBLE PRECISION NOT NULL,
  "currency"         TEXT NOT NULL DEFAULT 'MYR',
  "spentAmount"      DOUBLE PRECISION NOT NULL DEFAULT 0,
  "remainingAmount"  DOUBLE PRECISION NOT NULL DEFAULT 0,
  "category"         "ExpenseCategory",
  "departmentId"     TEXT,
  "alertThreshold"   DOUBLE PRECISION NOT NULL DEFAULT 0.8,
  "strictLimit"      BOOLEAN NOT NULL DEFAULT false,
  "approvedById"     TEXT,
  "approvedByName"   TEXT,
  "approvedAt"       TIMESTAMP(3),
  "notes"            TEXT,
  "tags"             TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "createdAt"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"        TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Budget_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "Budget_code_key" ON "Budget"("code");
CREATE INDEX IF NOT EXISTS "Budget_name_idx" ON "Budget"("name");
CREATE INDEX IF NOT EXISTS "Budget_code_idx" ON "Budget"("code");
CREATE INDEX IF NOT EXISTS "Budget_status_idx" ON "Budget"("status");
CREATE INDEX IF NOT EXISTS "Budget_fiscalYear_idx" ON "Budget"("fiscalYear");
CREATE INDEX IF NOT EXISTS "Budget_category_idx" ON "Budget"("category");
CREATE INDEX IF NOT EXISTS "Budget_departmentId_idx" ON "Budget"("departmentId");
CREATE INDEX IF NOT EXISTS "Budget_startDate_idx" ON "Budget"("startDate");
CREATE INDEX IF NOT EXISTS "Budget_endDate_idx" ON "Budget"("endDate");

-- ── Vendor ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Vendor" (
  "id"               TEXT NOT NULL,
  "name"             TEXT NOT NULL,
  "code"             TEXT,
  "description"      TEXT,
  "contactPerson"    TEXT,
  "email"            TEXT,
  "phone"            TEXT,
  "website"          TEXT,
  "address"          TEXT,
  "city"             TEXT,
  "state"            TEXT,
  "postalCode"       TEXT,
  "country"          TEXT DEFAULT 'Malaysia',
  "taxId"            TEXT,
  "bankName"         TEXT,
  "bankAccount"      TEXT,
  "paymentTerms"     TEXT,
  "category"         TEXT,
  "tags"             TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "isActive"         BOOLEAN NOT NULL DEFAULT true,
  "totalPurchases"   DOUBLE PRECISION NOT NULL DEFAULT 0,
  "purchaseCount"    INTEGER NOT NULL DEFAULT 0,
  "lastPurchaseDate" TIMESTAMP(3),
  "notes"            TEXT,
  "createdById"      TEXT,
  "createdByName"    TEXT,
  "createdAt"        TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"        TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Vendor_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "Vendor_code_key" ON "Vendor"("code");
CREATE INDEX IF NOT EXISTS "Vendor_name_idx" ON "Vendor"("name");
CREATE INDEX IF NOT EXISTS "Vendor_code_idx" ON "Vendor"("code");
CREATE INDEX IF NOT EXISTS "Vendor_category_idx" ON "Vendor"("category");
CREATE INDEX IF NOT EXISTS "Vendor_isActive_idx" ON "Vendor"("isActive");
CREATE INDEX IF NOT EXISTS "Vendor_createdAt_idx" ON "Vendor"("createdAt");

-- ── Expense ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Expense" (
  "id"                 TEXT NOT NULL,
  "title"              TEXT NOT NULL,
  "description"        TEXT,
  "category"           "ExpenseCategory" NOT NULL,
  "status"             "ExpenseStatus" NOT NULL DEFAULT 'DRAFT',
  "amount"             DOUBLE PRECISION NOT NULL,
  "currency"           TEXT NOT NULL DEFAULT 'MYR',
  "taxAmount"          DOUBLE PRECISION DEFAULT 0,
  "totalAmount"        DOUBLE PRECISION,
  "budgetId"           TEXT,
  "vendorId"           TEXT,
  "vendorInvoiceNo"    TEXT,
  "expenseDate"        TIMESTAMP(3) NOT NULL,
  "dueDate"            TIMESTAMP(3),
  "paidDate"           TIMESTAMP(3),
  "paymentMethod"      "PaymentMethod",
  "paymentReference"   TEXT,
  "bankAccount"        TEXT,
  "submittedById"      TEXT,
  "submittedByName"    TEXT,
  "submittedAt"        TIMESTAMP(3),
  "approvedById"       TEXT,
  "approvedByName"     TEXT,
  "approvedAt"         TIMESTAMP(3),
  "rejectionReason"    TEXT,
  "receiptUrl"         TEXT,
  "receiptFileName"    TEXT,
  "attachmentUrls"     TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "attachmentMetadata" JSONB,
  "notes"              TEXT,
  "tags"               TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "isRecurring"        BOOLEAN NOT NULL DEFAULT false,
  "recurringExpenseId" TEXT,
  "academicYear"       TEXT,
  "term"               TEXT,
  "departmentId"       TEXT,
  "relatedClassId"     TEXT,
  "relatedSubjectId"   TEXT,
  "createdAt"          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"          TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Expense_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "Expense_vendorInvoiceNo_key" ON "Expense"("vendorInvoiceNo");
CREATE UNIQUE INDEX IF NOT EXISTS "Expense_paymentReference_key" ON "Expense"("paymentReference");
CREATE INDEX IF NOT EXISTS "Expense_category_idx" ON "Expense"("category");
CREATE INDEX IF NOT EXISTS "Expense_status_idx" ON "Expense"("status");
CREATE INDEX IF NOT EXISTS "Expense_expenseDate_idx" ON "Expense"("expenseDate");
CREATE INDEX IF NOT EXISTS "Expense_dueDate_idx" ON "Expense"("dueDate");
CREATE INDEX IF NOT EXISTS "Expense_vendorId_idx" ON "Expense"("vendorId");
CREATE INDEX IF NOT EXISTS "Expense_budgetId_idx" ON "Expense"("budgetId");
CREATE INDEX IF NOT EXISTS "Expense_submittedById_idx" ON "Expense"("submittedById");
CREATE INDEX IF NOT EXISTS "Expense_academicYear_idx" ON "Expense"("academicYear");
CREATE INDEX IF NOT EXISTS "Expense_term_idx" ON "Expense"("term");
CREATE INDEX IF NOT EXISTS "Expense_isRecurring_idx" ON "Expense"("isRecurring");
CREATE INDEX IF NOT EXISTS "Expense_createdAt_idx" ON "Expense"("createdAt");

-- ── BillPayment ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "BillPayment" (
  "id"              TEXT NOT NULL,
  "expenseId"       TEXT NOT NULL,
  "paymentNumber"   TEXT NOT NULL,
  "amount"          DOUBLE PRECISION NOT NULL,
  "currency"        TEXT NOT NULL DEFAULT 'MYR',
  "paymentMethod"   "PaymentMethod" NOT NULL,
  "paymentDate"     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "referenceNumber" TEXT,
  "bankAccount"     TEXT,
  "receiptUrl"      TEXT,
  "receiptFileName" TEXT,
  "approvedById"    TEXT,
  "approvedByName"  TEXT,
  "approvedAt"      TIMESTAMP(3),
  "notes"           TEXT,
  "createdAt"       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"       TIMESTAMP(3) NOT NULL,
  CONSTRAINT "BillPayment_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "BillPayment_paymentNumber_key" ON "BillPayment"("paymentNumber");
CREATE INDEX IF NOT EXISTS "BillPayment_expenseId_idx" ON "BillPayment"("expenseId");
CREATE INDEX IF NOT EXISTS "BillPayment_paymentDate_idx" ON "BillPayment"("paymentDate");
CREATE INDEX IF NOT EXISTS "BillPayment_paymentMethod_idx" ON "BillPayment"("paymentMethod");
CREATE INDEX IF NOT EXISTS "BillPayment_paymentNumber_idx" ON "BillPayment"("paymentNumber");

-- ── RecurringExpense ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "RecurringExpense" (
  "id"                 TEXT NOT NULL,
  "title"              TEXT NOT NULL,
  "description"        TEXT,
  "category"           "ExpenseCategory" NOT NULL,
  "status"             "ExpenseStatus" NOT NULL DEFAULT 'DRAFT',
  "amount"             DOUBLE PRECISION NOT NULL,
  "currency"           TEXT NOT NULL DEFAULT 'MYR',
  "taxAmount"          DOUBLE PRECISION DEFAULT 0,
  "totalAmount"        DOUBLE PRECISION,
  "vendorId"           TEXT,
  "frequency"          "RecurringExpenseFrequency" NOT NULL,
  "startDate"          TIMESTAMP(3) NOT NULL,
  "endDate"            TIMESTAMP(3),
  "dayOfMonth"         INTEGER,
  "occurrenceCount"    INTEGER,
  "paymentMethod"      "PaymentMethod",
  "budgetId"           TEXT,
  "approvedById"       TEXT,
  "approvedByName"     TEXT,
  "approvedAt"         TIMESTAMP(3),
  "nextOccurrenceDate" TIMESTAMP(3),
  "lastGeneratedDate"  TIMESTAMP(3),
  "totalGenerated"     INTEGER NOT NULL DEFAULT 0,
  "notes"              TEXT,
  "tags"               TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "createdAt"          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"          TIMESTAMP(3) NOT NULL,
  CONSTRAINT "RecurringExpense_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "RecurringExpense_category_idx" ON "RecurringExpense"("category");
CREATE INDEX IF NOT EXISTS "RecurringExpense_status_idx" ON "RecurringExpense"("status");
CREATE INDEX IF NOT EXISTS "RecurringExpense_frequency_idx" ON "RecurringExpense"("frequency");
CREATE INDEX IF NOT EXISTS "RecurringExpense_startDate_idx" ON "RecurringExpense"("startDate");
CREATE INDEX IF NOT EXISTS "RecurringExpense_endDate_idx" ON "RecurringExpense"("endDate");
CREATE INDEX IF NOT EXISTS "RecurringExpense_nextOccurrenceDate_idx" ON "RecurringExpense"("nextOccurrenceDate");
CREATE INDEX IF NOT EXISTS "RecurringExpense_createdAt_idx" ON "RecurringExpense"("createdAt");

-- ── Donor ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Donor" (
  "id"                TEXT NOT NULL,
  "donorCode"         TEXT NOT NULL,
  "name"              TEXT NOT NULL,
  "email"             TEXT,
  "phone"             TEXT,
  "organization"      TEXT,
  "donorType"         TEXT NOT NULL DEFAULT 'INDIVIDUAL',
  "category"          TEXT,
  "address"           TEXT,
  "city"              TEXT,
  "state"             TEXT,
  "postalCode"        TEXT,
  "country"           TEXT DEFAULT 'Malaysia',
  "preferredContact"  TEXT DEFAULT 'EMAIL',
  "doNotContact"      BOOLEAN NOT NULL DEFAULT false,
  "isActive"          BOOLEAN NOT NULL DEFAULT true,
  "taxId"             TEXT,
  "receiptPreference" TEXT DEFAULT 'EMAIL',
  "notes"             TEXT,
  "tags"              TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "createdById"       TEXT,
  "createdByName"     TEXT,
  "createdAt"         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"         TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Donor_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "Donor_donorCode_key" ON "Donor"("donorCode");
CREATE INDEX IF NOT EXISTS "Donor_donorCode_idx" ON "Donor"("donorCode");
CREATE INDEX IF NOT EXISTS "Donor_email_idx" ON "Donor"("email");
CREATE INDEX IF NOT EXISTS "Donor_donorType_idx" ON "Donor"("donorType");
CREATE INDEX IF NOT EXISTS "Donor_organization_idx" ON "Donor"("organization");

-- ── DonationCampaign ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "DonationCampaign" (
  "id"             TEXT NOT NULL,
  "name"           TEXT NOT NULL,
  "description"    TEXT,
  "goalAmount"     DOUBLE PRECISION NOT NULL,
  "currency"       TEXT NOT NULL DEFAULT 'MYR',
  "status"         "CampaignStatus" NOT NULL DEFAULT 'DRAFT',
  "startDate"      TIMESTAMP(3) NOT NULL,
  "endDate"        TIMESTAMP(3) NOT NULL,
  "targetAudience" TEXT,
  "raisedAmount"   DOUBLE PRECISION NOT NULL DEFAULT 0,
  "donorCount"     INTEGER NOT NULL DEFAULT 0,
  "coverImage"     TEXT,
  "notes"          TEXT,
  "tags"           TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "createdById"    TEXT,
  "createdByName"  TEXT,
  "createdAt"      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"      TIMESTAMP(3) NOT NULL,
  CONSTRAINT "DonationCampaign_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "DonationCampaign_status_idx" ON "DonationCampaign"("status");
CREATE INDEX IF NOT EXISTS "DonationCampaign_startDate_idx" ON "DonationCampaign"("startDate");
CREATE INDEX IF NOT EXISTS "DonationCampaign_endDate_idx" ON "DonationCampaign"("endDate");

-- ── Donation ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "Donation" (
  "id"                 TEXT NOT NULL,
  "donationNumber"     TEXT NOT NULL,
  "amount"             DOUBLE PRECISION NOT NULL,
  "currency"           TEXT NOT NULL DEFAULT 'MYR',
  "donationType"       "DonationType" NOT NULL DEFAULT 'ONE_TIME',
  "status"             "DonationStatus" NOT NULL DEFAULT 'PENDING',
  "purpose"            TEXT,
  "designation"        TEXT,
  "donorId"            TEXT NOT NULL,
  "campaignId"         TEXT,
  "paymentMethod"      TEXT,
  "paymentReference"   TEXT,
  "receiptNumber"      TEXT,
  "donationDate"       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "receivedDate"       TIMESTAMP(3),
  "processedDate"      TIMESTAMP(3),
  "isTaxDeductible"    BOOLEAN NOT NULL DEFAULT true,
  "taxReceiptAmount"   DOUBLE PRECISION,
  "notes"              TEXT,
  "acknowledgmentSent" BOOLEAN NOT NULL DEFAULT false,
  "createdAt"          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"          TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Donation_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "Donation_donationNumber_key" ON "Donation"("donationNumber");
CREATE UNIQUE INDEX IF NOT EXISTS "Donation_receiptNumber_key" ON "Donation"("receiptNumber");
CREATE INDEX IF NOT EXISTS "Donation_donorId_idx" ON "Donation"("donorId");
CREATE INDEX IF NOT EXISTS "Donation_campaignId_idx" ON "Donation"("campaignId");
CREATE INDEX IF NOT EXISTS "Donation_status_idx" ON "Donation"("status");
CREATE INDEX IF NOT EXISTS "Donation_donationDate_idx" ON "Donation"("donationDate");
CREATE INDEX IF NOT EXISTS "Donation_donationNumber_idx" ON "Donation"("donationNumber");

-- ── DonationReceipt ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "DonationReceipt" (
  "id"                  TEXT NOT NULL,
  "donationId"          TEXT NOT NULL,
  "receiptNumber"       TEXT NOT NULL,
  "receiptDate"         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "recipientName"       TEXT NOT NULL,
  "recipientAddress"    TEXT,
  "recipientEmail"      TEXT,
  "amount"              DOUBLE PRECISION NOT NULL,
  "currency"            TEXT NOT NULL DEFAULT 'MYR',
  "isTaxDeductible"     BOOLEAN NOT NULL DEFAULT true,
  "taxDeductibleAmount" DOUBLE PRECISION,
  "taxId"               TEXT,
  "notes"               TEXT,
  "createdAt"           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"           TIMESTAMP(3) NOT NULL,
  CONSTRAINT "DonationReceipt_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "DonationReceipt_donationId_key" ON "DonationReceipt"("donationId");
CREATE UNIQUE INDEX IF NOT EXISTS "DonationReceipt_receiptNumber_key" ON "DonationReceipt"("receiptNumber");
CREATE INDEX IF NOT EXISTS "DonationReceipt_receiptNumber_idx" ON "DonationReceipt"("receiptNumber");
CREATE INDEX IF NOT EXISTS "DonationReceipt_receiptDate_idx" ON "DonationReceipt"("receiptDate");

-- ── FeeStructure ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "FeeStructure" (
  "id"                 TEXT NOT NULL,
  "name"               TEXT NOT NULL,
  "description"        TEXT,
  "academicYear"       INTEGER NOT NULL,
  "term"               TEXT,
  "status"             "FeeStructureStatus" NOT NULL DEFAULT 'DRAFT',
  "currency"           TEXT NOT NULL DEFAULT 'MYR',
  "effectiveFromDate"  TIMESTAMP(3) NOT NULL,
  "effectiveToDate"    TIMESTAMP(3),
  "applyToClasses"     BOOLEAN NOT NULL DEFAULT false,
  "applyToBoarders"    BOOLEAN NOT NULL DEFAULT false,
  "applyToDayStudents" BOOLEAN NOT NULL DEFAULT false,
  "notes"              TEXT,
  "tags"               TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "createdById"        TEXT,
  "createdByName"      TEXT,
  "createdAt"          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"          TIMESTAMP(3) NOT NULL,
  CONSTRAINT "FeeStructure_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "FeeStructure_status_idx" ON "FeeStructure"("status");
CREATE INDEX IF NOT EXISTS "FeeStructure_academicYear_idx" ON "FeeStructure"("academicYear");
CREATE INDEX IF NOT EXISTS "FeeStructure_effectiveFromDate_idx" ON "FeeStructure"("effectiveFromDate");

-- ── FeeItem ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "FeeItem" (
  "id"                TEXT NOT NULL,
  "name"              TEXT NOT NULL,
  "description"       TEXT,
  "amount"            DOUBLE PRECISION NOT NULL,
  "currency"          TEXT NOT NULL DEFAULT 'MYR',
  "frequency"         "FeeFrequency" NOT NULL DEFAULT 'ONE_TIME',
  "applicableTo"      TEXT NOT NULL DEFAULT 'ALL',
  "classIds"          TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "dueDate"           TIMESTAMP(3),
  "dueDaysAfterStart" INTEGER,
  "budgetId"          TEXT,
  "order"             INTEGER NOT NULL DEFAULT 0,
  "isActive"          BOOLEAN NOT NULL DEFAULT true,
  "createdById"       TEXT,
  "createdByName"     TEXT,
  "createdAt"         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"         TIMESTAMP(3) NOT NULL,
  "feeStructureId"    TEXT NOT NULL,
  CONSTRAINT "FeeItem_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "FeeItem_feeStructureId_idx" ON "FeeItem"("feeStructureId");
CREATE INDEX IF NOT EXISTS "FeeItem_isActive_idx" ON "FeeItem"("isActive");

-- ── FeeAssignment ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "FeeAssignment" (
  "id"                TEXT NOT NULL,
  "studentId"         TEXT NOT NULL,
  "feeItemId"         TEXT NOT NULL,
  "feeStructureId"    TEXT NOT NULL,
  "baseAmount"        DOUBLE PRECISION NOT NULL,
  "discountAmount"    DOUBLE PRECISION NOT NULL DEFAULT 0,
  "totalAmount"       DOUBLE PRECISION NOT NULL,
  "paidAmount"        DOUBLE PRECISION NOT NULL DEFAULT 0,
  "outstandingAmount" DOUBLE PRECISION NOT NULL,
  "status"            "FeeStatus" NOT NULL DEFAULT 'PENDING',
  "dueDate"           TIMESTAMP(3) NOT NULL,
  "paidDate"          TIMESTAMP(3),
  "feePaymentId"      TEXT,
  "notes"             TEXT,
  "createdAt"         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"         TIMESTAMP(3) NOT NULL,
  CONSTRAINT "FeeAssignment_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "FeeAssignment_feePaymentId_key" ON "FeeAssignment"("feePaymentId");
CREATE INDEX IF NOT EXISTS "FeeAssignment_studentId_idx" ON "FeeAssignment"("studentId");
CREATE INDEX IF NOT EXISTS "FeeAssignment_feeItemId_idx" ON "FeeAssignment"("feeItemId");
CREATE INDEX IF NOT EXISTS "FeeAssignment_feeStructureId_idx" ON "FeeAssignment"("feeStructureId");
CREATE INDEX IF NOT EXISTS "FeeAssignment_status_idx" ON "FeeAssignment"("status");
CREATE INDEX IF NOT EXISTS "FeeAssignment_dueDate_idx" ON "FeeAssignment"("dueDate");

-- ── FeeDiscount ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "FeeDiscount" (
  "id"                   TEXT NOT NULL,
  "name"                 TEXT NOT NULL,
  "description"          TEXT,
  "discountType"         "FeeDiscountType" NOT NULL,
  "value"                DOUBLE PRECISION NOT NULL,
  "applyToAllStructures" BOOLEAN NOT NULL DEFAULT false,
  "feeStructureIds"      TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "classIds"             TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  "minSiblings"          INTEGER,
  "requireBoarding"      BOOLEAN NOT NULL DEFAULT false,
  "minGpa"               DOUBLE PRECISION,
  "validFrom"            TIMESTAMP(3) NOT NULL,
  "validTo"              TIMESTAMP(3),
  "isActive"             BOOLEAN NOT NULL DEFAULT true,
  "createdById"          TEXT,
  "createdByName"        TEXT,
  "createdAt"            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"            TIMESTAMP(3) NOT NULL,
  "feeStructureId"       TEXT NOT NULL,
  CONSTRAINT "FeeDiscount_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "FeeDiscount_feeStructureId_idx" ON "FeeDiscount"("feeStructureId");
CREATE INDEX IF NOT EXISTS "FeeDiscount_isActive_idx" ON "FeeDiscount"("isActive");
CREATE INDEX IF NOT EXISTS "FeeDiscount_validFrom_idx" ON "FeeDiscount"("validFrom");

-- ── FeePaymentPlan ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "FeePaymentPlan" (
  "id"                   TEXT NOT NULL,
  "name"                 TEXT NOT NULL,
  "description"          TEXT,
  "feeStructureId"       TEXT NOT NULL,
  "studentId"            TEXT NOT NULL,
  "totalAmount"          DOUBLE PRECISION NOT NULL,
  "currency"             TEXT NOT NULL DEFAULT 'MYR',
  "numberOfInstallments" INTEGER NOT NULL,
  "installmentFrequency" TEXT NOT NULL DEFAULT 'MONTHLY',
  "firstInstallmentDue"  TIMESTAMP(3) NOT NULL,
  "status"               "InstallmentStatus" NOT NULL DEFAULT 'PENDING',
  "agreedById"           TEXT,
  "agreedByName"         TEXT,
  "agreedAt"             TIMESTAMP(3),
  "notes"                TEXT,
  "createdAt"            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"            TIMESTAMP(3) NOT NULL,
  CONSTRAINT "FeePaymentPlan_pkey" PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "FeePaymentPlan_studentId_idx" ON "FeePaymentPlan"("studentId");
CREATE INDEX IF NOT EXISTS "FeePaymentPlan_feeStructureId_idx" ON "FeePaymentPlan"("feeStructureId");
CREATE INDEX IF NOT EXISTS "FeePaymentPlan_status_idx" ON "FeePaymentPlan"("status");

-- ── FeeInstallment ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "FeeInstallment" (
  "id"                TEXT NOT NULL,
  "paymentPlanId"     TEXT NOT NULL,
  "installmentNumber" INTEGER NOT NULL,
  "amount"            DOUBLE PRECISION NOT NULL,
  "dueDate"           TIMESTAMP(3) NOT NULL,
  "paidDate"          TIMESTAMP(3),
  "status"            "InstallmentStatus" NOT NULL DEFAULT 'DUE',
  "feePaymentId"      TEXT,
  "notes"             TEXT,
  "createdAt"         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"         TIMESTAMP(3) NOT NULL,
  CONSTRAINT "FeeInstallment_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "FeeInstallment_feePaymentId_key" ON "FeeInstallment"("feePaymentId");
CREATE INDEX IF NOT EXISTS "FeeInstallment_paymentPlanId_idx" ON "FeeInstallment"("paymentPlanId");
CREATE INDEX IF NOT EXISTS "FeeInstallment_status_idx" ON "FeeInstallment"("status");
CREATE INDEX IF NOT EXISTS "FeeInstallment_dueDate_idx" ON "FeeInstallment"("dueDate");

-- ── FeePayment: new nullable link columns to FeeAssignment/FeeInstallment ──
-- (FeeAssignment.feePaymentId / FeeInstallment.feePaymentId above are the
-- informational back-reference scalars; these two columns on FeePayment are
-- the actual Prisma-managed relation side, per schema.prisma's `@relation`
-- fields/references placement.)
ALTER TABLE "FeePayment" ADD COLUMN IF NOT EXISTS "assignmentId" TEXT;
ALTER TABLE "FeePayment" ADD COLUMN IF NOT EXISTS "installmentId" TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS "FeePayment_assignmentId_key" ON "FeePayment"("assignmentId");
CREATE UNIQUE INDEX IF NOT EXISTS "FeePayment_installmentId_key" ON "FeePayment"("installmentId");
CREATE INDEX IF NOT EXISTS "FeePayment_assignmentId_idx" ON "FeePayment"("assignmentId");
CREATE INDEX IF NOT EXISTS "FeePayment_installmentId_idx" ON "FeePayment"("installmentId");

-- ── Foreign keys ─────────────────────────────────────────────────────────────
DO $$ BEGIN
  ALTER TABLE "Expense" ADD CONSTRAINT "Expense_vendorId_fkey"
    FOREIGN KEY ("vendorId") REFERENCES "Vendor"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "Expense" ADD CONSTRAINT "Expense_recurringExpenseId_fkey"
    FOREIGN KEY ("recurringExpenseId") REFERENCES "RecurringExpense"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "Expense" ADD CONSTRAINT "Expense_budgetId_fkey"
    FOREIGN KEY ("budgetId") REFERENCES "Budget"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "BillPayment" ADD CONSTRAINT "BillPayment_expenseId_fkey"
    FOREIGN KEY ("expenseId") REFERENCES "Expense"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "RecurringExpense" ADD CONSTRAINT "RecurringExpense_vendorId_fkey"
    FOREIGN KEY ("vendorId") REFERENCES "Vendor"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "Donation" ADD CONSTRAINT "Donation_donorId_fkey"
    FOREIGN KEY ("donorId") REFERENCES "Donor"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "Donation" ADD CONSTRAINT "Donation_campaignId_fkey"
    FOREIGN KEY ("campaignId") REFERENCES "DonationCampaign"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "DonationReceipt" ADD CONSTRAINT "DonationReceipt_donationId_fkey"
    FOREIGN KEY ("donationId") REFERENCES "Donation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "FeeItem" ADD CONSTRAINT "FeeItem_budgetId_fkey"
    FOREIGN KEY ("budgetId") REFERENCES "Budget"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "FeeItem" ADD CONSTRAINT "FeeItem_feeStructureId_fkey"
    FOREIGN KEY ("feeStructureId") REFERENCES "FeeStructure"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "FeeAssignment" ADD CONSTRAINT "FeeAssignment_studentId_fkey"
    FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "FeeAssignment" ADD CONSTRAINT "FeeAssignment_feeItemId_fkey"
    FOREIGN KEY ("feeItemId") REFERENCES "FeeItem"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "FeeAssignment" ADD CONSTRAINT "FeeAssignment_feeStructureId_fkey"
    FOREIGN KEY ("feeStructureId") REFERENCES "FeeStructure"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "FeeDiscount" ADD CONSTRAINT "FeeDiscount_feeStructureId_fkey"
    FOREIGN KEY ("feeStructureId") REFERENCES "FeeStructure"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "FeePaymentPlan" ADD CONSTRAINT "FeePaymentPlan_feeStructureId_fkey"
    FOREIGN KEY ("feeStructureId") REFERENCES "FeeStructure"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "FeePaymentPlan" ADD CONSTRAINT "FeePaymentPlan_studentId_fkey"
    FOREIGN KEY ("studentId") REFERENCES "Student"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "FeeInstallment" ADD CONSTRAINT "FeeInstallment_paymentPlanId_fkey"
    FOREIGN KEY ("paymentPlanId") REFERENCES "FeePaymentPlan"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "FeePayment" ADD CONSTRAINT "FeePayment_assignmentId_fkey"
    FOREIGN KEY ("assignmentId") REFERENCES "FeeAssignment"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE "FeePayment" ADD CONSTRAINT "FeePayment_installmentId_fkey"
    FOREIGN KEY ("installmentId") REFERENCES "FeeInstallment"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
