import { useEffect, useState } from 'react';
import { Link } from 'react-router';
import { ArrowDown, ArrowUp, ListVideo, Plus } from 'lucide-react';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { apiGet, apiSend } from '../../lib/api';
import { usePermissions, useUser } from '../../lib/permissions';
import type { VideoLesson } from '../../lib/video/types';
import AnimatedContent from '../react-bits/AnimatedContent';
type Playlist = { id: string; title: string; videoIds: string[]; lessons: { id: string; title: string }[]; canManage: boolean };
export function VideoPlaylists({ videos = [], currentVideoId }: { videos?: VideoLesson[]; currentVideoId?: string }) {
  const { isAdmin, isTeacher } = usePermissions(); const { user } = useUser();
  const [rows, setRows] = useState<Playlist[]>([]); const [error, setError] = useState('');
  const [revision, setRevision] = useState(0); const [editing, setEditing] = useState(false);
  const [id, setId] = useState<string | null>(null); const [title, setTitle] = useState(''); const [ids, setIds] = useState<string[]>([]); const [saving, setSaving] = useState(false);
  useEffect(() => { const controller = new AbortController(); setError(''); apiGet<Playlist[]>('/api/video-playlists', { signal: controller.signal }).then(d => { if (!controller.signal.aborted) setRows(Array.isArray(d) ? d : []); }).catch(e => { if (!controller.signal.aborted) setError(e.message); }); return () => controller.abort(); }, [revision]);
  const manageable = videos.filter(v => isAdmin || v.uploadedById === user?.id);
  const relevant = currentVideoId ? rows.filter(p => p.videoIds.includes(currentVideoId)) : rows;
  const move = (i: number, direction: number) => setIds(values => { const copy = [...values]; const to = i + direction; if (to < 0 || to >= copy.length) return copy; [copy[i], copy[to]] = [copy[to], copy[i]]; return copy; });
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await apiSend(`/api/video-playlists${id ? `/${id}` : ''}`, id ? 'PUT' : 'POST', { title, videoIds: ids }); setEditing(false); setRevision(r => r + 1); toast.success('Playlist saved'); } catch (e: any) { toast.error(e.message); } finally { setSaving(false); } };
  return <section className="space-y-3" aria-label="Video playlists"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="flex items-center gap-2 text-base font-semibold text-foreground"><ListVideo className="size-4" />{currentVideoId ? 'Continue This Unit' : 'Playlists & Units'}</h2>{!currentVideoId && (isAdmin || isTeacher) && <Button size="sm" variant="outline" onClick={() => { setEditing(true); setId(null); setTitle(''); setIds([]); }}><Plus className="size-3" />New Playlist</Button>}</div>
    {error && <div role="alert" className="rounded-lg border border-border bg-card p-3 text-sm text-destructive">{error}<Button size="sm" variant="ghost" onClick={() => setRevision(r => r + 1)}>Retry Playlists</Button></div>}
    {editing && <AnimatedContent className="rounded-xl border border-border bg-card p-4"><form onSubmit={save} className="space-y-3"><label className="block space-y-2 text-sm"><span>Playlist Title</span><Input required maxLength={100} value={title} onChange={e => setTitle(e.target.value)} /></label><p className="text-xs text-muted-foreground">Select your lessons, then use the arrows to set their order.</p><div className="max-h-64 space-y-2 overflow-y-auto">{manageable.map(v => <label key={v.id} className="flex items-start gap-2 text-sm"><input type="checkbox" checked={ids.includes(v.id)} onChange={e => setIds(values => e.target.checked ? [...values, v.id] : values.filter(x => x !== v.id))} /><span>{v.title}</span></label>)}</div><ol className="space-y-1">{ids.map((value, i) => <li key={value} className="flex items-center gap-2 rounded-md border border-border p-2 text-sm"><span className="min-w-0 flex-1 break-words">{i + 1}. {videos.find(v => v.id === value)?.title || 'Unavailable lesson'}</span><Button type="button" size="icon" variant="ghost" aria-label={`Move lesson ${i + 1} up`} disabled={i === 0} onClick={() => move(i, -1)}><ArrowUp className="size-4" /></Button><Button type="button" size="icon" variant="ghost" aria-label={`Move lesson ${i + 1} down`} disabled={i === ids.length - 1} onClick={() => move(i, 1)}><ArrowDown className="size-4" /></Button></li>)}</ol><div className="flex justify-end gap-2"><Button type="button" variant="ghost" disabled={saving} onClick={() => setEditing(false)}>Cancel Playlist</Button><Button type="submit" disabled={saving || !ids.length}>{saving ? 'Saving…' : 'Save Playlist'}</Button></div></form></AnimatedContent>}
    {relevant.length > 0 ? <div className="grid gap-3 md:grid-cols-2">{relevant.map(p => <details key={p.id} open={!!currentVideoId} className="rounded-xl border border-border bg-card p-4"><summary className="cursor-pointer text-sm font-semibold text-card-foreground">{p.title} <span className="font-normal text-muted-foreground">· {p.lessons.length} lessons</span></summary><ol className="mt-3 space-y-1">{p.lessons.map((v, i) => <li key={v.id}><Link aria-current={v.id === currentVideoId ? 'page' : undefined} className={`block min-h-10 rounded-md px-2 py-2 text-sm hover:bg-muted ${v.id === currentVideoId ? 'bg-muted font-semibold' : 'text-academic-teal'}`} to={`/videos/${v.id}`}>{i + 1}. {v.title}</Link></li>)}</ol>{!currentVideoId && p.canManage && <div className="mt-2 flex gap-2"><Button size="sm" variant="outline" onClick={() => { setId(p.id); setTitle(p.title); setIds(p.videoIds); setEditing(true); }}>Edit Playlist</Button><Button size="sm" variant="ghost" onClick={async () => { if (!window.confirm(`Delete playlist “${p.title}”? Lessons will not be deleted.`)) return; try { await apiSend(`/api/video-playlists/${p.id}`, 'DELETE'); setRevision(r => r + 1); } catch (e: any) { toast.error(e.message); } }}>Delete Playlist</Button></div>}</details>)}</div> : !error && <p className="text-sm text-muted-foreground">{currentVideoId ? 'This lesson is not part of a unit yet.' : 'No playlists yet. Group lessons into a learning sequence.'}</p>}
  </section>;
}
