import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import jwt from 'jsonwebtoken';
import fs from 'node:fs';
const url = process.env.FINANCE_TEST_DATABASE_URL;
if (!url || new URL(url).hostname !== '127.0.0.1' || new URL(url).port !== '55439') throw new Error('Disposable database required');
const db = new PrismaClient({ adapter: new PrismaPg({ connectionString: url }) });
const user = await db.user.upsert({ where: { email: 'finance-test@example.test' }, update: {}, create: { email: 'finance-test@example.test', firstName: 'Finance', lastName: 'Reviewer', role: 'ADMIN' } });
await db.schoolProfile.create({ data: { name: 'MRLC Finance Test School', currency: 'MYR', backupEnabled: false, cursorEffect: 'NONE' } });
const donor = await db.donor.create({ data: { name: 'Community Education Fund', donorCode: 'QA-' + Date.now() } });
const budget = await db.budget.create({ data: { name: 'Learning materials', fiscalYear: 2026, startDate: new Date('2026-01-01'), endDate: new Date('2026-12-31'), currency: 'MYR', allocatedAmount: 20000, remainingAmount: 20000, strictLimit: true } });
const pending = await db.expense.create({ data: { title: 'Classroom learning supplies', category: 'ACADEMIC', amount: 1200, taxAmount: 72, expenseDate: new Date('2026-08-01'), status: 'PENDING_APPROVAL', submittedById: 'another-officer', submittedByName: 'Finance preparer', budgetId: budget.id } });
const payable = await db.expense.create({ data: { title: 'September classroom rent', category: 'FACILITY', amount: 2500, taxAmount: 0, expenseDate: new Date('2026-09-01'), status: 'APPROVED', submittedById: 'another-officer' } });
await db.donation.create({ data: { donorId: donor.id, donationNumber: 'QA-CASH-' + Date.now(), amount: 18000, status: 'RECEIVED', donationDate: new Date('2026-07-01'), receivedDate: new Date('2026-08-10'), currency: 'MYR' } });
await db.donation.create({ data: { donorId: donor.id, donationNumber: 'QA-KIND-' + Date.now(), amount: 99999, donationType: 'IN_KIND', status: 'RECEIVED', donationDate: new Date('2026-08-01'), currency: 'MYR' } });
await db.donation.create({ data: { donorId: donor.id, donationNumber: 'QA-USD-' + Date.now(), amount: 99999, status: 'RECEIVED', donationDate: new Date('2026-08-01'), currency: 'USD' } });
const token = jwt.sign({ userId: user.id, email: user.email, role: 'ADMIN' }, 'finance-disposable-test-secret-only', { expiresIn: '2h' });
const studentToken = jwt.sign({ userId: 'test-student', email: 'student@example.test', role: 'STUDENT' }, 'finance-disposable-test-secret-only', { expiresIn: '2h' });
fs.writeFileSync('/tmp/mrlc-finance-fixtures.json', JSON.stringify({ token, studentToken, payable: payable.id, pending: pending.id, donor: donor.id }));
await db.$disconnect(); console.log('Disposable fixtures ready');
